using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BMR_MVC.Models
{
    public class QueryCored
    {
        String query;
        public String GetJob() {
            query = @"SELECT JOB_SYS_ID
                    ,CAST((OPERATE_PERCENT+CHECK_PERCENT) AS nvarchar)+'|'+ISNULL(CAST(JOB_APPR_PD_BCR_STATUS AS nvarchar)+'|','|')+ISNULL(USER_APPR_PD_JOB_USER_NAME+'|','|')+ISNULL(JOB_APPR_PD_BCR_DT,'') AS APPR_JOB_PD
                    ,CAST((OPERATE_PERCENT+CHECK_PERCENT) AS nvarchar)+'|'+ISNULL(CAST(JOB_APPR_QA_BCR_STATUS AS nvarchar)+'|','|')+ISNULL(USER_APPR_QA_JOB_USER_NAME+'|','|')+ISNULL(JOB_APPR_QA_BCR_DT,'') AS APPR_JOB_QA
					,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,BMR_VERSION
					,JOB_ITEM_CODE+'|'+JOB_ITEM_NAME+'|'+'R'+cast(BMR_RV1 as nvarchar)+'-'+CAST(BMR_RV2 AS NVARCHAR)+'/'+CONVERT(varchar,BMR_RV_DATE,4)+
					ISNULL('|'+CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108),'|')+
					ISNULL('|'+CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108),'|') as JOB_ITEM_NAME2
					,CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108) AS JOB_START_DT
					,CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108) AS JOB_END_DT
                    ,PARSENAME(CONVERT(varchar, CAST(JOB_BATCH_SIZE AS money), 1), 2)+' '+JOB_UOM as JOB_BATCH_SIZE
                    ,JOB_STATUS
                    ,SUBSTRING(BCRR_CC_RUN_NO,0,LEN(BCRR_CC_RUN_NO)) AS BCRR_CC_RUN_NO
                    ,SUBSTRING(BCRR_CC_EQUIPMENT_NO,0,LEN(BCRR_CC_EQUIPMENT_NO)) AS BCRR_CC_EQUIPMENT_NO
                    ,SUBSTRING(BCRR_CC_EQUIPMENT_NAME,0,LEN(BCRR_CC_EQUIPMENT_NAME)) AS BCRR_CC_EQUIPMENT_NAME
                    ,SUBSTRING(BCRR_STEP_NO,0,LEN(BCRR_STEP_NO)) AS  BCRR_STEP_NO
                    ,SUBSTRING(BCRR_RUN_NO,0,LEN(BCRR_RUN_NO)) AS  BCRR_RUN_NO
                    ,SUBSTRING(BCRR_STEP_DESC,0,LEN(BCRR_STEP_DESC)) AS BCRR_STEP_DESC
					,SUBSTRING(BCRR_CC_GROUP_CLEAN_ID,0,LEN(BCRR_CC_GROUP_CLEAN_ID)) AS BCRR_CC_GROUP_CLEAN_ID
					,SUBSTRING(BCRR_CC_GROUP_CHECK_ID,0,LEN(BCRR_CC_GROUP_CHECK_ID)) AS BCRR_CC_GROUP_CHECK_ID
					,SUBSTRING(BCRR_GROUP_OPERATE_ID,0,LEN(BCRR_GROUP_OPERATE_ID)) AS BCRR_GROUP_OPERATE_ID
					,SUBSTRING(BCRR_GROUP_CHECK_ID,0,LEN(BCRR_GROUP_CHECK_ID)) AS BCRR_GROUP_CHECK_ID
					,SUBSTRING(BCRR_REQ_TEMP_YN,0,LEN(BCRR_REQ_TEMP_YN)) as BCRR_REQ_TEMP_YN
					,SUBSTRING(BCRR_REQ_HUMUDITY_YN,0,LEN(BCRR_REQ_HUMUDITY_YN)) as BCRR_REQ_HUMUDITY_YN
					,SUBSTRING(BCRR_REQ_PRESS_YN,0,LEN(BCRR_REQ_PRESS_YN)) as BCRR_REQ_PRESS_YN
					,SUBSTRING(BCRR_REQ_VACC_YN,0,LEN(BCRR_REQ_VACC_YN)) BCRR_REQ_VACC_YN
					,SUBSTRING(BCRR_REQ_START_STOP_YN,0,LEN(BCRR_REQ_START_STOP_YN)) BCRR_REQ_START_STOP_YN
					,SUBSTRING(BCRR_REQ_WEIGHT_YN,0,LEN(BCRR_REQ_WEIGHT_YN)) BCRR_REQ_WEIGHT_YN
					,SUBSTRING(BCRR_REQ_WEIGHT_SAMPLE_YN,0,LEN(BCRR_REQ_WEIGHT_SAMPLE_YN)) BCRR_REQ_WEIGHT_SAMPLE_YN
					,SUBSTRING(USER_NAME_CC_CLEAN,0,LEN(USER_NAME_CC_CLEAN)) AS USER_NAME_CC_CLEAN
					,SUBSTRING(USER_NAME_CC_CLEAN_DT,0,LEN(USER_NAME_CC_CLEAN_DT)) AS  USER_NAME_CC_CLEAN_DT
					,SUBSTRING(USER_NAME_CC_CHECK,0,LEN(USER_NAME_CC_CHECK)) AS USER_NAME_CC_CHECK
					,SUBSTRING(USER_NAME_CC_CHECK_DT,0,LEN(USER_NAME_CC_CHECK_DT)) AS USER_NAME_CC_CHECK_DT
					,SUBSTRING(USER_NAME_BCR_OPERATE,0,LEN(USER_NAME_BCR_OPERATE)) AS USER_NAME_BCR_OPERATE
					,SUBSTRING(USER_NAME_BCR_OPERATE_DT,0,LEN(USER_NAME_BCR_OPERATE_DT)) AS USER_NAME_BCR_OPERATE_DT
					,SUBSTRING(USER_NAME_BCR_CHECK,0,LEN(USER_NAME_BCR_CHECK)) AS USER_NAME_BCR_CHECK
					,SUBSTRING(USER_NAME_BCR_CHECK_DT,0,LEN(USER_NAME_BCR_CHECK_DT)) USER_NAME_BCR_CHECK_DT
                    ,SUBSTRING(BCRR_REQ_IMAGE_YN,0,LEN(BCRR_REQ_IMAGE_YN)) AS BCRR_REQ_IMAGE_YN
                    ,SUBSTRING(BCRR_CC_REQ_IMAGE_YN,0,LEN(BCRR_CC_REQ_IMAGE_YN)) as BCRR_CC_REQ_IMAGE_YN
					,OPERATE_PERCENT,CHECK_PERCENT
                    FROM(
                    SELECT distinct JOB_SYS_ID,JOB_APPR_PD_BCR_STATUS,JOB_APPR_QA_BCR_STATUS,JOB_CR_DT,BMR_RV1,BMR_RV2,BMR_RV_DATE
					,CONVERT(varchar,NULLIF(JOB_APPR_PD_BCR_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_APPR_PD_BCR_DT,''), 108)  AS  JOB_APPR_PD_BCR_DT
					,USER_APPR_PD_JOB.USER_NAME AS USER_APPR_PD_JOB_USER_NAME
					,CONVERT(varchar,NULLIF(JOB_APPR_QA_BCR_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_APPR_QA_BCR_DT,''), 108)  AS  JOB_APPR_QA_BCR_DT
					,USER_APPR_QA_JOB.USER_NAME AS USER_APPR_QA_JOB_USER_NAME
					,JOB_START_DT,BMR_VERSION,JOB_END_DT,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,JOB_BATCH_SIZE,JOB_STATUS,JOB_UOM
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_TEMP_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_TEMP_YN
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_HUMUDITY_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_HUMUDITY_YN
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_PRESS_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_PRESS_YN
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_VACC_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_VACC_YN
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_START_STOP_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_START_STOP_YN
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_WEIGHT_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_WEIGHT_YN
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_WEIGHT_SAMPLE_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_WEIGHT_SAMPLE_YN
                    ,STUFF((SELECT  ISNULL(cast(t2.BCRR_REQ_IMAGE_YN as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_REQ_IMAGE_YN
                    ,STUFF((SELECT  cast(t2.BCRR_CC_RUN_NO as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.BCRR_CC_BMR_H_SYS_ID AND t2.BCRR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_CC_RUN_NO
                    ,STUFF((SELECT  cast(t2.BCRR_CC_EQUIPMENT_NO as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.BCRR_CC_BMR_H_SYS_ID AND t2.BCRR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') BCRR_CC_EQUIPMENT_NO
                    ,STUFF((SELECT  cast(t2.BCRR_CC_EQUIPMENT_NAME as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.BCRR_CC_BMR_H_SYS_ID AND t2.BCRR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_CC_EQUIPMENT_NAME
                    ,STUFF((SELECT  cast(t2.BCRR_CC_REQ_IMAGE_YN as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.BCRR_CC_BMR_H_SYS_ID AND t2.BCRR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_CC_REQ_IMAGE_YN
                    ,STUFF((SELECT  cast(t2.BCRR_STEP_NO as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_STEP_NO
                    ,STUFF((SELECT  cast(t2.BCRR_RUN_NO as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_RUN_NO
                    ,STUFF((SELECT  cast(t2.BCRR_STEP_DESC as nvarchar(max))+'|' from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.BCRR_JOB_SYS_ID order by  t2.BCRR_STEP_NO,BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_STEP_DESC
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_CC_GROUP_CLEAN_ID as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.BCRR_CC_BMR_H_SYS_ID AND t2.BCRR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_CC_GROUP_CLEAN_ID
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_CC_GROUP_CHECK_ID as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.BCRR_CC_BMR_H_SYS_ID AND t2.BCRR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_CC_GROUP_CHECK_ID
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_GROUP_OPERATE_ID as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND t2.BCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_GROUP_OPERATE_ID
					,STUFF((SELECT  ISNULL(cast(t2.BCRR_GROUP_CHECK_ID as nvarchar(max))+'|','|') from BMR_BCR_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.BCRR_BMR_H_SYS_ID AND t2.BCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.BCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') BCRR_GROUP_CHECK_ID
					,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_BCR_RUN_JOB_CC 
							LEFT JOIN BMR_BCR_RUN_JOB_CC_CHECK  ON BCRR_CC_RUN_NO=BCR_CC_RJCHK_RUN_NO and BCRR_CC_JOB_SYS_ID = BCR_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON BCR_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN
				 	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(BCR_CC_RJCHK_CLEAN_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_CC_RJCHK_CLEAN_BY_DT,''), 108) +'|','|')
							from BMR_BCR_RUN_JOB_CC 
							LEFT JOIN BMR_BCR_RUN_JOB_CC_CHECK  ON BCRR_CC_RUN_NO=BCR_CC_RJCHK_RUN_NO and BCRR_CC_JOB_SYS_ID = BCR_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON BCR_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN_DT
					,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_BCR_RUN_JOB_CC 
							LEFT JOIN BMR_BCR_RUN_JOB_CC_CHECK  ON BCRR_CC_RUN_NO=BCR_CC_RJCHK_RUN_NO and BCRR_CC_JOB_SYS_ID = BCR_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON BCR_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK
					,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(BCR_CC_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_CC_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
							from BMR_BCR_RUN_JOB_CC 
							LEFT JOIN BMR_BCR_RUN_JOB_CC_CHECK  ON BCRR_CC_RUN_NO=BCR_CC_RJCHK_RUN_NO and BCRR_CC_JOB_SYS_ID = BCR_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON BCR_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK_DT
					,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_BCR_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_BCR_RUN_JOB_CHECK  ON BCRR_RUN_NO=BCR_RJCHK_RUN_NO AND BCRR_STEP_NO = BCR_RJCHK_STEP and BCRR_JOB_SYS_ID = BCR_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON BCR_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_JOB_SYS_ID
                            order by BCRR_STEP_NO,BCRR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_BCR_OPERATE
					,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(BCR_RJCHK_OPERATE_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_RJCHK_OPERATE_BY_DT,''), 108) +'|','|')
							from BMR_BCR_RUN_JOB_PROCEDURE
								LEFT JOIN BMR_BCR_RUN_JOB_CHECK  ON BCRR_RUN_NO=BCR_RJCHK_RUN_NO AND BCRR_STEP_NO = BCR_RJCHK_STEP and BCRR_JOB_SYS_ID = BCR_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON BCR_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_JOB_SYS_ID
                            order by BCRR_STEP_NO,BCRR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_BCR_OPERATE_DT
					,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_BCR_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_BCR_RUN_JOB_CHECK  ON BCRR_RUN_NO=BCR_RJCHK_RUN_NO AND BCRR_STEP_NO = BCR_RJCHK_STEP and BCRR_JOB_SYS_ID = BCR_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON BCR_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_JOB_SYS_ID
                            order by BCRR_STEP_NO,BCRR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_BCR_CHECK
					,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(BCR_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
							from BMR_BCR_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_BCR_RUN_JOB_CHECK  ON BCRR_RUN_NO=BCR_RJCHK_RUN_NO AND BCRR_STEP_NO = BCR_RJCHK_STEP and BCRR_JOB_SYS_ID = BCR_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON BCR_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = BCRR_BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_JOB_SYS_ID
                            order by BCRR_STEP_NO,BCRR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_BCR_CHECK_DT
                    FROM SHOW_BCR_JOB
					LEFT JOIN BMR_RUN_JOB ON JOB_SYS_ID = CHECK_JOB_SYS_ID
					LEFT JOIN BMR_HEAD ON JOB_H_SYS_ID = BMR_H_SYS_ID
					LEFT JOIN BMR_USER_CTRL USER_APPR_PD_JOB ON JOB_APPR_PD_BCR_USR_ID=USER_APPR_PD_JOB.USER_SYS_ID
					LEFT JOIN BMR_USER_CTRL USER_APPR_QA_JOB ON JOB_APPR_QA_BCR_USR_ID=USER_APPR_QA_JOB.USER_SYS_ID
                    where JOB_APPR_PD_MX_STATUS = 1 and JOB_APPR_QA_MX_STATUS = 1
                    )DATA1
					 LEFT JOIN  (
					SELECT JOB_SYS_ID AS JOB_SYS_ID_2
							,CASE WHEN SUM(COUNT_)<=0 THEN 0 ELSE CAST((CAST(SUM(OPERATE) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) END as OPERATE_PERCENT
							,CASE WHEN SUM(COUNT_)<=0 THEN 0 ELSE CAST((CAST(SUM(CHECK_) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) END as CHECK_PERCENT
							FROM(
									SELECT JOB_SYS_ID,COUNT(BCR_CC_RJCHK_CLEAN_BY_USR_ID) AS OPERATE,COUNT(BCR_CC_RJCHK_CHECK_BY_USR_ID) AS CHECK_
									,COUNT(BCRR_CC_SYS_ID) AS COUNT_
									FROM  BMR_RUN_JOB
									LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
									LEFT JOIN BMR_BCR_RUN_JOB_CC ON BCRR_CC_BMR_H_SYS_ID = BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_CC_JOB_SYS_ID
									LEFT JOIN BMR_BCR_RUN_JOB_CC_CHECK ON BCR_CC_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND BCRR_CC_RUN_NO = BCR_CC_RJCHK_RUN_NO
                                    WHERE BCRR_CC_RUN_NO >0
									GROUP BY JOB_SYS_ID
									UNION
									SELECT JOB_SYS_ID,COUNT(BCR_RJCHK_OPERATE_BY_USR_ID) AS OPERATE,COUNT(BCR_RJCHK_CHECK_BY_USR_ID) AS CHECK_
									,COUNT(BCRR_SYS_ID) AS COUNT_
									FROM  BMR_RUN_JOB
									LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
									LEFT JOIN BMR_BCR_RUN_JOB_PROCEDURE ON BCRR_BMR_H_SYS_ID = BMR_H_SYS_ID AND JOB_SYS_ID = BCRR_JOB_SYS_ID
									LEFT JOIN BMR_BCR_RUN_JOB_CHECK ON BCR_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND BCR_RJCHK_STEP = BCRR_STEP_NO AND BCRR_RUN_NO = BCR_RJCHK_RUN_NO
                                    WHERE BCRR_RUN_NO > 0
									GROUP BY JOB_SYS_ID
							)DATA1
							GROUP BY JOB_SYS_ID
					)DATA2 ON DATA2.JOB_SYS_ID_2 = DATA1.JOB_SYS_ID
                    order by JOB_CR_DT desc";
            return query;
        }
        public String InsertRunJobTime()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_TIME @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@START_DT = @P_START_DT,@END_DT = @P_END_DT,@USER_ID = @P_USER_ID,@LENGTH = @P_LENGTH,@STATUS_OPERATE = @P_STATUS_OPERATE";
            return query;
        }
        public String QueryRunJobTime()
        {
            query = @"SELECT BCR_RJDT_JOB_SYS_ID,BCR_RJDT_STEP_NO,BCR_RJDT_RUN_NO,BCR_RJDT_LIST_NO
                    ,CONVERT(varchar,NULLIF(BCR_RJDT_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_RJDT_START_DT,''), 108) as BCR_RJDT_START_DT
                    ,CONVERT(varchar,NULLIF(BCR_RJDT_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_RJDT_END_DT,''), 108) as BCR_RJDT_END_DT 
                    ,USER_NAME_OPERATE,USER_NAME_CHECK,CONVERT(varchar,NULLIF(BCR_RJDT_CHECK_BY_DT_CHECK,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(BCR_RJDT_CHECK_BY_DT_CHECK,''), 108)  AS BCR_RJDT_CHECK_BY_DT_CHECK
                    FROM BMR_BCR_RUN_JOB_TIME
                    LEFT JOIN (
			                    SELECT BCR_RJDT_JOB_SYS_ID AS BCR_RJDT_JOB_SYS_ID_OPRATE,BCR_RJDT_STEP_NO AS BCR_RJDT_STEP_NO_OPERATE
			                    ,BCR_RJDT_RUN_NO AS BCR_RJDT_RUN_NO_OPERATE,BCR_RJDT_LIST_NO AS BCR_RJDT_LIST_NO_OPERATE,USER_NAME AS USER_NAME_OPERATE
			                    FROM BMR_BCR_RUN_JOB_TIME LEFT JOIN BMR_USER_CTRL ON BCR_RJDT_OPERATE_BY_USR_ID = USER_SYS_ID
		                      )DATAOPERATE ON BCR_RJDT_JOB_SYS_ID_OPRATE = BCR_RJDT_JOB_SYS_ID 
			                      and BCR_RJDT_STEP_NO_OPERATE = BCR_RJDT_STEP_NO
			                      and BCR_RJDT_RUN_NO_OPERATE = BCR_RJDT_RUN_NO 
			                      and BCR_RJDT_LIST_NO_OPERATE = BCR_RJDT_LIST_NO
                    LEFT JOIN (
	  		                    SELECT BCR_RJDT_JOB_SYS_ID AS BCR_RJDT_JOB_SYS_ID_CHECK,BCR_RJDT_STEP_NO AS BCR_RJDT_STEP_NO_CHECK,BCR_RJDT_RUN_NO AS BCR_RJDT_RUN_NO_CHECK
			                    ,BCR_RJDT_LIST_NO AS BCR_RJDT_LIST_NO_CHECK,USER_NAME AS USER_NAME_CHECK,BCR_RJDT_CHECK_BY_DT as BCR_RJDT_CHECK_BY_DT_CHECK
			                    FROM BMR_BCR_RUN_JOB_TIME LEFT JOIN BMR_USER_CTRL ON BCR_RJDT_CHECK_BY_USR_ID = USER_SYS_ID
		                      )DATACHECK ON BCR_RJDT_JOB_SYS_ID_CHECK = BCR_RJDT_JOB_SYS_ID 
			                      and BCR_RJDT_STEP_NO_CHECK = BCR_RJDT_STEP_NO
			                      and BCR_RJDT_RUN_NO_CHECK = BCR_RJDT_RUN_NO 
			  and BCR_RJDT_LIST_NO_CHECK = BCR_RJDT_LIST_NO
                WHERE BCR_RJDT_JOB_SYS_ID = @P_JOB_SYS_ID AND BCR_RJDT_STEP_NO = @P_STEP AND BCR_RJDT_RUN_NO = @P_RUN_NO";
            return query;
        }
            public String InsertTemp()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_TEMP @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@TEMP = @P_TEMP,@USER_ID = @P_USER_ID";
            return query;
        }
        public String QueryRunJobGetTemp()
        {
            //Scalar
            query = "SELECT BCR_RJT_TEMP FROM BMR_BCR_RUN_JOB_TEMP WHERE BCR_RJT_JOB_SYS_ID  = @P_JOB_SYS_ID AND BCR_RJT_STEP_NO = @P_STEP AND BCR_RJT_RUN_NO= @P_RUN_NO";
            return query;
        }
        public String QueryRunJobGetPressure()
        {
            //Scalar
            query = "SELECT BCR_RJP_PRESSURE FROM BMR_BCR_RUN_JOB_PRESSURE WHERE BCR_RJP_JOB_SYS_ID = @P_JOB_SYS_ID AND BCR_RJP_STEP_NO = @P_STEP AND BCR_RJP_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String InsertPressure()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_PRESSURE @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@PRESSURE = @P_PRESSURE,@USER_ID = @P_USER_ID";
            return query;
        }
        public String InsertHumidity()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_HUMIDITY @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@HUMIDITY = @P_HUMIDITY,@USER_ID = @P_USER_ID";
            return query;
        }
        public String QueryRunJobGetHumidity()
        {
            //Scalar
            query = "SELECT BCR_RJH_HUMIDITY FROM BMR_BCR_RUN_JOB_HUMIDITY WHERE BCR_RJH_JOB_SYS_ID = @P_JOB_SYS_ID AND BCR_RJH_STEP_NO = @P_STEP AND BCR_RJH_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String CheckBcrCCCleanChk()
        {
            query = "EXEC BCR_CC_CLEAN_CHECK @USERID = @P_USERID,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String CheckBcrCCChkChk()
        {
            query = "EXEC BCR_CC_CHECK_CHECK @USERID = @P_USERID,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String CheckBcrOperateChk()
        {
            query = "EXEC BCR_OPERATE_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String CheckBcrChkChk()
        {
            query = "EXEC BCR_CHECK_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String BcrTimeOperateCheck()
        {
            query = "EXEC BCR_TIME_OPERATE_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@TOKEN = @P_TOKEN,@PASSWORD = @P_PASSWORD";
            return query;
        }
        public String BcrTimeCheckCheck()
        {
            query = "EXEC BCR_TIME_CHECK_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@TOKEN = @P_TOKEN,@PASSWORD = @P_PASSWORD";
            return query;
        }
        public String QueryRunJobImage()
        {
            query = "SELECT BCR_RJPT_SYS_ID,BCR_RJPT_IMAGE_NAME,BCR_RJPT_LIST_NO,BCR_RJPT_IMAGE_PATH,BCR_RJPT_REMARK FROM BMR_BCR_RUN_JOB_PICTURE WHERE BCR_RJPT_JOB_SYS_ID =@P_SYS_ID AND BCR_RJPT_STEP_NO = @P_STEP AND BCR_RJPT_RUN_NO =@P_RUNNO";
            return query;
        }
        public String InsertRunJobImage()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_IMAGE @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@LENGTH = @P_LENGTH,@IMAGE_NAME = @P_IMAGE_NAME,@IMAGE_PATH = @P_IMAGE_PATH,@IMAGE_REMARK = @P_REMARK,@USER_ID = @P_USERID";
            return query;
        }
        public String QueryCCRunJobImage()
        {
            query = @"SELECT BCR_CC_RJPT_SYS_ID,BCR_CC_RJPT_IMAGE_NAME,BCR_CC_RJPT_LIST_NO,BCR_CC_RJPT_IMAGE_PATH,BCR_CC_RJPT_REMARK
                      FROM BMR_BCR_RUN_JOB_CC_PICTURE
                      WHERE BCR_CC_RJPT_JOB_SYS_ID =@P_SYS_ID  AND BCR_CC_RJPT_RUN_NO =@P_RUNNO";
            return query;
        }
        public String CCInsertRunJobImage()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_CC_IMAGE @JOB_SYS_ID = @P_JOB_SYS_ID,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@LENGTH = @P_LENGTH,@IMAGE_NAME = @P_IMAGE_NAME,@IMAGE_PATH = @P_IMAGE_PATH,@IMAGE_REMARK = @P_REMARK,@USER_ID = @P_USERID";
            return query;
        }
        public String CCUpdateRunJobImage()
        {
            //Remark
            query = "UPDATE BMR_BCR_RUN_JOB_CC_PICTURE SET BCR_CC_RJPT_REMARK = @P_REMARK,BCR_CC_RJPT_UPD_USR_ID = @P_USER_ID,BCR_CC_RJPT_UPD_DT = SYSDATETIME() WHERE BCR_CC_RJPT_JOB_SYS_ID = @P_JOB_SYS_ID AND  BCR_CC_RJPT_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String ApprPdJob()
        {
            query = "EXEC APPR_PD_BCR_RUN_JOB @JOB_SYS_ID = @P_JOB_SYS_ID,@USER_ID = @P_USER_ID ,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String ApprQaJob()
        {
            query = "EXEC APPR_QA_BCR_RUN_JOB @JOB_SYS_ID = @P_JOB_SYS_ID,@USER_ID = @P_USER_ID ,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String InsertRunJobCC()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_CC @JOB_SYS_ID = @P_JOB_SYS_ID,@RUN_NO = @P_RUN_NO,@EQUIPMENT_NO = @P_EQUIPMENT_NO,@EQUIPMENT_NAME = @P_EQUIPMENT_NAME,@GROUP_CLEAN = @P_GROUP_CLEAN,@GROUP_CHECK = @P_GROUP_CHECK,@REQ_IMAGE_YN = @P_REQ_IMAGE_YN,@USER_ID = @P_USER_ID";
            return query;
        }
        public String InsertRunJobWeight()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_WEIGHT @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@TANK_AMOUNT = @P_TANK_AMOUNT,@NET = @P_NET,@THEORETICAL = @P_THEORETICAL,@YIELD = @P_YIELD,@USR_ID = @P_USR_ID";
            return query;
        }
        public String GetWeight()
        {
            query = @"SELECT * FROM BMR_BCR_RUN_JOB_WEIGHT
                    WHERE BCR_RJW_JOB_SYS_ID = @P_JOB_SYS_ID 
                    AND BCR_RJW_STEP_NO =  @P_STEP_NO
                    AND BCR_RJW_RUN_NO = @P_RUN_NO";
            return query;
        }

        public String InsertRunJobWeightOfSample()
        {
            query = "EXEC INSERT_BMR_BCR_RUN_JOB_WEIGHT_SAMPLE @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@WEIGHT = @P_WEIGHT,@USER_ID = @P_USER_ID";
            return query;
        }
        public String QueryRunJobWeightOfSample()
        {
            //Scalar
            query = "SELECT BCR_RJWS_WEIGHT FROM BMR_BCR_RUN_JOB_WEIGHT_SAMPLE WHERE BCR_RJWS_JOB_SYS_ID = @P_JOB_SYS_ID AND BCR_RJWS_STEP_NO = @P_STEP AND BCR_RJWS_RUN_NO = @P_RUN_NO";
            return query;
        }
    }
}