using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BMR_MVC.Models
{
    public class QuerMixing
    {
        String query;
        public String QueryGetRunJobHead()
        {
            query = @"SELECT JOB_SYS_ID,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,JOB_BATCH_SIZE,JOB_UOM,JOB_REMARK
                        ,CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108) AS JOB_START_DT 
                        ,CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108) AS JOB_END_DT  
                      FROM BMR_RUN_JOB where JOB_SYS_ID = @P_JOB_SYS_ID";
            return query;
        }
        public String UpdateRunjobHead()
        {
            query = @"EXEC UPDATE_BMR_RUN_JOB @JOB_SYS_ID = @P_JOB_SYS_ID,@LOT = @P_LOT,@BATCH_SIZE = @P_BATCH_SIZE,@UOM = @P_UOM,@START_DT = @P_START_DT,@END_DT = @P_END_DT,@REMARK = @P_REMARK";
            return query;
        }
        public String DeleteJob() {
            query = "EXEC DELETE_BMR_RUN_JOB @SYS_ID = @P_SYS_ID";
            return query;
        }
        public String QueryGetGroup()
        {
            query = "select GROUP_ID,GROUP_NAME,CASE WHEN  LEN(GROUP_DESC)>0 THEN ' ('+GROUP_DESC+')' ELSE NULL END AS GROUP_DESC from BMR_USER_GROUP";
            return query;
        }
        public String QueryCheckLogin()
        {
            //query = "select USER_SYS_ID,USER_NAME from BMR_USER_CTRL where USER_LOGIN = @P_USER_LOGIN and USER_PASS = @P_USER_PASS";
            query = "EXEC BMR_LOGIN @USER_LOGIN = @P_USER_LOGIN,@PASSWORD = @P_PASSWORD,@TOKEN = @P_TOKEN";
            return query;
        }
        public String CheckMxCCCleanChk() {
            query = "EXEC MX_CC_CLEAN_CHECK @USERID = @P_USERID,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String CheckMxCCCheckChk()
        {
            query = "EXEC MX_CC_CHECK_CHECK @USERID = @P_USERID,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String CheckMxOperateChk()
        {
            query = "EXEC MX_OPERATE_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String CheckMxCheckChk()
        {
            query = "EXEC MX_CHECK_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String MxWeightOperateCheck()
        {
            query = "EXEC MX_WEIGHT_OPERATE_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@TOKEN = @P_TOKEN,@PASSWORD = @P_PASSWORD";
            return query;
        }
        public String MxWeightCheckCheck()
        {
            query = "EXEC MX_WEIGHT_CHECK_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@TOKEN = @P_TOKEN,@PASSWORD = @P_PASSWORD";
            return query;
        }
        public String MxTimeOperateCheck()
        {
            query = "EXEC MX_TIME_OPERATE_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@TOKEN = @P_TOKEN,@PASSWORD = @P_PASSWORD";
            return query;
        }
        public String MxTimeCheckCheck()
        {
            query = "EXEC MX_TIME_CHECK_CHECK @USERID = @P_USERID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@JOB_SYS_ID = @P_JOB_SYS_ID,@TOKEN = @P_TOKEN,@PASSWORD = @P_PASSWORD";
            return query;
        }
        public String QueryGetJob() {
            //query = "SELECT BMR_ITEM_CODE,BMR_ITEM_NAME,JOB_LOT,JOB_BATCH_SIZE,JOB_STATUS FROM BMR_RUN_JOB  LEFT JOIN BMR_HEAD ON JOB_H_SYS_ID = BMR_H_SYS_ID";
            //       query = @"SELECT JOB_SYS_ID,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,BMR_VERSION
            //,CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108) AS JOB_START_DT
            //,CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108) AS JOB_END_DT
            //               ,PARSENAME(CONVERT(varchar, CAST(JOB_BATCH_SIZE AS money), 1), 2)+' '+JOB_UOM as JOB_BATCH_SIZE
            //               ,JOB_STATUS
            //               ,SUBSTRING(CCR_RUN_NO,0,LEN(CCR_RUN_NO)) AS CCR_RUN_NO
            //               ,SUBSTRING(CCR_EQUIPMENT_NO,0,LEN(CCR_EQUIPMENT_NO)) AS CCR_EQUIPMENT_NO
            //               ,SUBSTRING(CCR_EQUIPMENT_NAME,0,LEN(CCR_EQUIPMENT_NAME)) AS CCR_EQUIPMENT_NAME
            //               ,SUBSTRING(MXS_STEP,0,LEN(MXS_STEP)) AS  MXS_STEP
            //               ,SUBSTRING(MXS_RUN_NO,0,LEN(MXS_RUN_NO)) AS  MXS_RUN_NO
            //               ,SUBSTRING(MXS_STEP_DESC,0,LEN(MXS_STEP_DESC)) AS MXS_STEP_DESC
            //               ,SUBSTRING(USER_NAME_CC_CLEAN,0,LEN(USER_NAME_CC_CLEAN)) AS USER_NAME_CC_CLEAN
            //               ,SUBSTRING(USER_NAME_CC_CHECK,0,LEN(USER_NAME_CC_CHECK)) AS USER_NAME_CC_CHECK
            //               ,SUBSTRING(USER_NAME_MX_OPERATE,0,LEN(USER_NAME_MX_OPERATE)) AS USER_NAME_MX_OPERATE
            //,SUBSTRING(USER_NAME_MX_OPERATE_DT,0,LEN(USER_NAME_MX_OPERATE_DT)) AS USER_NAME_MX_OPERATE_DT
            //               ,SUBSTRING(USER_NAME_MX_CHECK,0,LEN(USER_NAME_MX_CHECK)) AS USER_NAME_MX_CHECK
            //               ,SUBSTRING(USER_NAME_MX_CHECK_DT,0,LEN(USER_NAME_MX_CHECK_DT)) AS USER_NAME_MX_CHECK_DT
            //,SUBSTRING(USER_NAME_CC_CLEAN_DT,0,LEN(USER_NAME_CC_CLEAN_DT)) AS USER_NAME_CC_CLEAN_DT
            //               ,SUBSTRING(USER_NAME_CC_CHECK_DT,0,LEN(USER_NAME_CC_CHECK_DT)) AS USER_NAME_CC_CHECK_DT
            //,OPERATE_PERCENT,CHECK_PERCENT
            //               FROM(
            //               SELECT distinct JOB_SYS_ID,JOB_START_DT,BMR_VERSION,JOB_END_DT,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,JOB_BATCH_SIZE,JOB_STATUS,JOB_UOM
            //                    ,STUFF((SELECT  cast(t2.CCR_RUN_NO as nvarchar(max))+'|' from CLEAN_CONTROL_RECORD t2 where JOB_H_SYS_ID = t2.CCR_BMR_H_SYS_ID order by t2.CCR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_RUN_NO
            //                    ,STUFF((SELECT  cast(t2.CCR_EQUIPMENT_NO as nvarchar(max))+'|' from CLEAN_CONTROL_RECORD t2 where JOB_H_SYS_ID = t2.CCR_BMR_H_SYS_ID order by t2.CCR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') CCR_EQUIPMENT_NO
            //                    ,STUFF((SELECT  cast(t2.CCR_EQUIPMENT_NAME as nvarchar(max))+'|' from CLEAN_CONTROL_RECORD t2 where JOB_H_SYS_ID = t2.CCR_BMR_H_SYS_ID order by t2.CCR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_EQUIPMENT_NAME
            //                    ,STUFF((SELECT  cast(t2.MXS_STEP as nvarchar(max))+'|' from MIX_STEP t2 where JOB_H_SYS_ID = t2.MXS_H_SYS_ID order by  t2.MXS_STEP,MXS_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STEP
            //                    ,STUFF((SELECT  cast(t2.MXS_RUN_NO as nvarchar(max))+'|' from MIX_STEP t2 where JOB_H_SYS_ID = t2.MXS_H_SYS_ID order by  t2.MXS_STEP,MXS_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_RUN_NO
            //                    ,STUFF((SELECT  cast(t2.MXS_STEP_DESC as nvarchar(max))+'|' from MIX_STEP t2 where JOB_H_SYS_ID = t2.MXS_H_SYS_ID order by  t2.MXS_STEP,MXS_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STEP_DESC
            //	 ,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from CLEAN_CONTROL_RECORD 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCR_RUN_NO=MX_CC_RJCHK_RUN_NO AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN
            //,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_CC_RJCHK_CLEAN_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_CC_RJCHK_CLEAN_BY_DT,''), 108) +'|','|')
            //		from CLEAN_CONTROL_RECORD 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCR_RUN_NO=MX_CC_RJCHK_RUN_NO AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN_DT
            //	,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from CLEAN_CONTROL_RECORD 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCR_RUN_NO=MX_CC_RJCHK_RUN_NO AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK
            //	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_CC_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_CC_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
            //		from CLEAN_CONTROL_RECORD 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCR_RUN_NO=MX_CC_RJCHK_RUN_NO AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK_DT
            //	,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from MIX_STEP  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXS_RUN_NO=MX_RJCHK_RUN_NO AND MXS_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXS_H_SYS_ID
            //                       order by MXS_STEP,MXS_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_OPERATE
            //	,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from MIX_STEP  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXS_RUN_NO=MX_RJCHK_RUN_NO AND MXS_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXS_H_SYS_ID
            //                       order by MXS_STEP,MXS_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_CHECK
            //	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
            //		from MIX_STEP  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXS_RUN_NO=MX_RJCHK_RUN_NO AND MXS_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXS_H_SYS_ID
            //                       order by MXS_STEP,MXS_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_CHECK_DT
            //	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_RJCHK_OPERATE_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJCHK_OPERATE_BY_DT,''), 108) +'|','|')
            //		from MIX_STEP  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXS_RUN_NO=MX_RJCHK_RUN_NO AND MXS_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXS_H_SYS_ID
            //                       order by MXS_STEP,MXS_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_OPERATE_DT
            //               FROM BMR_RUN_JOB  LEFT JOIN BMR_HEAD ON JOB_H_SYS_ID = BMR_H_SYS_ID)DATA1
            // LEFT JOIN  (
            //SELECT JOB_SYS_ID AS JOB_SYS_ID_2
            //		,CAST((CAST(SUM(OPERATE) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) as OPERATE_PERCENT
            //		,CAST((CAST(SUM(CHECK_) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) as CHECK_PERCENT
            //		FROM(
            //				SELECT JOB_SYS_ID,COUNT(MX_CC_RJCHK_CLEAN_BY_USR_ID) AS OPERATE,COUNT(MX_CC_RJCHK_CHECK_BY_USR_ID) AS CHECK_
            //				,COUNT(CCR_SYS_ID) AS COUNT_
            //				FROM  BMR_RUN_JOB
            //				LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
            //				LEFT JOIN CLEAN_CONTROL_RECORD ON CCR_BMR_H_SYS_ID = BMR_H_SYS_ID
            //				LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK ON MX_CC_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND CCR_RUN_NO = MX_CC_RJCHK_RUN_NO
            //				GROUP BY JOB_SYS_ID
            //				UNION
            //				SELECT JOB_SYS_ID,COUNT(MX_RJCHK_OPERATE_BY_USR_ID) AS OPERATE,COUNT(MX_RJCHK_CHECK_BY_USR_ID) AS CHECK_
            //				,COUNT(MXS_SYS_ID) AS COUNTa_
            //				FROM  BMR_RUN_JOB
            //				LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
            //				LEFT JOIN MIX_STEP ON MXS_H_SYS_ID = BMR_H_SYS_ID
            //				LEFT JOIN BMR_MX_RUN_JOB_CHECK ON MX_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND MX_RJCHK_STEP = MXS_STEP AND MXS_RUN_NO = MX_RJCHK_RUN_NO
            //				GROUP BY JOB_SYS_ID
            //		)DATA1
            //		GROUP BY JOB_SYS_ID
            //)DATA2 ON DATA2.JOB_SYS_ID_2 = DATA1.JOB_SYS_ID";
            //       query = @"SELECT JOB_SYS_ID,SUBSTRING(CCR_GROUP_CLEAN_ID,0,LEN(CCR_GROUP_CLEAN_ID)) AS CCR_GROUP_CLEAN_ID
            //,SUBSTRING(CCR_GROUP_CHECK_ID,0,LEN(CCR_GROUP_CHECK_ID)) AS CCR_GROUP_CHECK_ID
            //,SUBSTRING(MXS_GROUP_OPERATE_ID,0,LEN(MXS_GROUP_OPERATE_ID)) AS MX_GROUP_OPRATE_ID
            //,SUBSTRING(MXS_GROUP_CHECK_ID,0,LEN(MXS_GROUP_CHECK_ID)) AS MXS_GROUP_CHECK_ID
            //,SUBSTRING(MXS_TEMP_YN,0,LEN(MXS_TEMP_YN)) as MXS_TEMP_YN
            //, SUBSTRING(MXS_HUMIDITY_YN,0,LEN(MXS_HUMIDITY_YN)) as MXS_HUMIDITY_YN
            //, SUBSTRING(MXS_PRESS_YN,0,LEN(MXS_PRESS_YN)) MXS_PRESS_YN
            //,SUBSTRING(MXS_VACC_YN,0,LEN(MXS_VACC_YN)) MXS_VACC_YN
            //               ,SUBSTRING(MXS_STARTSTOP_YN,0,LEN(MXS_STARTSTOP_YN)) as MXS_STARTSTOP_YN
            //,SUBSTRING(MXS_WEIGHT_YN,0,LEN(MXS_WEIGHT_YN)) as MXS_WEIGHT_YN
            //               ,SUBSTRING(MXS_WEIGHT_SAMPLE_YN,0,LEN(MXS_WEIGHT_SAMPLE_YN)) as MXS_REQ_WEIGHT_SAMPLE_YN
            //               ,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,BMR_VERSION
            //,CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108) AS JOB_START_DT
            //,CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108) AS JOB_END_DT
            //               ,PARSENAME(CONVERT(varchar, CAST(JOB_BATCH_SIZE AS money), 1), 2)+' '+JOB_UOM as JOB_BATCH_SIZE
            //               ,JOB_STATUS
            //               ,SUBSTRING(CCR_RUN_NO,0,LEN(CCR_RUN_NO)) AS CCR_RUN_NO
            //               ,SUBSTRING(CCR_EQUIPMENT_NO,0,LEN(CCR_EQUIPMENT_NO)) AS CCR_EQUIPMENT_NO
            //               ,SUBSTRING(CCR_EQUIPMENT_NAME,0,LEN(CCR_EQUIPMENT_NAME)) AS CCR_EQUIPMENT_NAME
            //               ,SUBSTRING(MXS_STEP,0,LEN(MXS_STEP)) AS  MXS_STEP
            //               ,SUBSTRING(MXS_RUN_NO,0,LEN(MXS_RUN_NO)) AS  MXS_RUN_NO
            //               ,SUBSTRING(MXS_STEP_DESC,0,LEN(MXS_STEP_DESC)) AS MXS_STEP_DESC
            //               ,SUBSTRING(USER_NAME_CC_CLEAN,0,LEN(USER_NAME_CC_CLEAN)) AS USER_NAME_CC_CLEAN
            //               ,SUBSTRING(USER_NAME_CC_CHECK,0,LEN(USER_NAME_CC_CHECK)) AS USER_NAME_CC_CHECK
            //               ,SUBSTRING(USER_NAME_MX_OPERATE,0,LEN(USER_NAME_MX_OPERATE)) AS USER_NAME_MX_OPERATE
            //,SUBSTRING(USER_NAME_MX_OPERATE_DT,0,LEN(USER_NAME_MX_OPERATE_DT)) AS USER_NAME_MX_OPERATE_DT
            //               ,SUBSTRING(USER_NAME_MX_CHECK,0,LEN(USER_NAME_MX_CHECK)) AS USER_NAME_MX_CHECK
            //               ,SUBSTRING(USER_NAME_MX_CHECK_DT,0,LEN(USER_NAME_MX_CHECK_DT)) AS USER_NAME_MX_CHECK_DT
            //,SUBSTRING(USER_NAME_CC_CLEAN_DT,0,LEN(USER_NAME_CC_CLEAN_DT)) AS USER_NAME_CC_CLEAN_DT
            //               ,SUBSTRING(USER_NAME_CC_CHECK_DT,0,LEN(USER_NAME_CC_CHECK_DT)) AS USER_NAME_CC_CHECK_DT
            //,OPERATE_PERCENT,CHECK_PERCENT
            //               FROM(
            //               SELECT distinct JOB_SYS_ID,JOB_START_DT,BMR_VERSION,JOB_END_DT,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,JOB_BATCH_SIZE,JOB_STATUS,JOB_UOM
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_TEMP_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_TEMP_YN
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_HUMUDITY_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_HUMIDITY_YN
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_PRESS_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_PRESS_YN
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_VACC_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_VACC_YN
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_STAR_STOP_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STARTSTOP_YN
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_WEIGHT as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_WEIGHT_YN
            //               ,STUFF((SELECT  ISNULL(cast(t2.MXSR_REQ_WEIGHT_SAMPLE_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_WEIGHT_SAMPLE_YN
            //,STUFF((SELECT  ISNULL(cast(t2.CCRR_GROUP_CLEAN_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.CCRR_BMR_H_SYS_ID AND t2.CCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.CCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_GROUP_CLEAN_ID
            //,STUFF((SELECT  ISNULL(cast(t2.CCRR_GROUP_CHECK_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.CCRR_BMR_H_SYS_ID AND t2.CCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.CCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_GROUP_CHECK_ID
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_GROUP_OPERATE_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_GROUP_OPERATE_ID
            //,STUFF((SELECT  ISNULL(cast(t2.MXSR_GROUP_CHECK_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_GROUP_CHECK_ID
            //               ,STUFF((SELECT  cast(t2.CCRR_RUN_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.CCRR_BMR_H_SYS_ID AND t2.CCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.CCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_RUN_NO
            //               ,STUFF((SELECT  cast(t2.CCRR_EQUIPMENT_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.CCRR_BMR_H_SYS_ID AND t2.CCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.CCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') CCR_EQUIPMENT_NO
            //               ,STUFF((SELECT  cast(t2.CCRR_EQUIPMENT_NAME as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.CCRR_BMR_H_SYS_ID AND t2.CCRR_JOB_SYS_ID = JOB_SYS_ID order by t2.CCRR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_EQUIPMENT_NAME
            //               ,STUFF((SELECT  cast(t2.MXSR_STEP as nvarchar(max))+'|' from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STEP
            //               ,STUFF((SELECT  cast(t2.MXSR_RUN_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_RUN_NO
            //               ,STUFF((SELECT  cast(t2.MXSR_STEP_DESC as nvarchar(max))+'|' from BMR_MX_RUN_JOB_MX t2 where JOB_H_SYS_ID = t2.MXSR_H_SYS_ID AND JOB_SYS_ID = t2.MXSR_JOB_SYS_ID order by  t2.MXSR_STEP,MXSR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STEP_DESC
            //,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from BMR_MX_RUN_JOB_CC 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCRR_RUN_NO=MX_CC_RJCHK_RUN_NO AND MX_CC_RJCHK_JOB_SYS_ID = CCRR_JOB_SYS_ID AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCRR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN
            //,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_CC_RJCHK_CLEAN_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_CC_RJCHK_CLEAN_BY_DT,''), 108) +'|','|')
            //		from BMR_MX_RUN_JOB_CC 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCRR_RUN_NO=MX_CC_RJCHK_RUN_NO AND MX_CC_RJCHK_JOB_SYS_ID = CCRR_JOB_SYS_ID AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCRR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN_DT
            //	,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from BMR_MX_RUN_JOB_CC 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCRR_RUN_NO=MX_CC_RJCHK_RUN_NO  AND MX_CC_RJCHK_JOB_SYS_ID = CCRR_JOB_SYS_ID AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCRR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK
            //	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_CC_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_CC_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
            //		from BMR_MX_RUN_JOB_CC 
            //		LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON CCRR_RUN_NO=MX_CC_RJCHK_RUN_NO AND MX_CC_RJCHK_JOB_SYS_ID = CCRR_JOB_SYS_ID  AND JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
            //		LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = CCRR_BMR_H_SYS_ID
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK_DT
            //	,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from BMR_MX_RUN_JOB_MX  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXSR_RUN_NO=MX_RJCHK_RUN_NO AND MXSR_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MXSR_JOB_SYS_ID AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXSR_H_SYS_ID
            //                       order by MXSR_STEP,MXSR_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_OPERATE
            //	,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
            //		from BMR_MX_RUN_JOB_MX  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXSR_RUN_NO=MX_RJCHK_RUN_NO AND MXSR_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MXSR_JOB_SYS_ID  AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXSR_H_SYS_ID
            //                       order by MXSR_STEP,MXSR_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_CHECK
            //	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
            //		from BMR_MX_RUN_JOB_MX  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXSR_RUN_NO=MX_RJCHK_RUN_NO AND MXSR_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MXSR_JOB_SYS_ID AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXSR_H_SYS_ID
            //                       order by MXSR_STEP,MXSR_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_CHECK_DT
            //	,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_RJCHK_OPERATE_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJCHK_OPERATE_BY_DT,''), 108) +'|','|')
            //		from BMR_MX_RUN_JOB_MX  
            //			LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXSR_RUN_NO=MX_RJCHK_RUN_NO AND MXSR_STEP = MX_RJCHK_STEP AND JOB_SYS_ID = MXSR_JOB_SYS_ID  AND JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
            //			LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
            //		WHERE BMR_H_SYS_ID = MXSR_H_SYS_ID
            //                       order by MXSR_STEP,MXSR_RUN_NO
            //		FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_OPERATE_DT
            //               FROM BMR_RUN_JOB  LEFT JOIN BMR_HEAD ON JOB_H_SYS_ID = BMR_H_SYS_ID)DATA1
            // LEFT JOIN  (
            //SELECT JOB_SYS_ID AS JOB_SYS_ID_2
            //		,CASE WHEN SUM(COUNT_)<=0 THEN 0 ELSE CAST((CAST(SUM(OPERATE) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) END as OPERATE_PERCENT
            //		,CASE WHEN SUM(COUNT_)<=0 THEN 0 ELSE CAST((CAST(SUM(CHECK_) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) END as CHECK_PERCENT
            //		FROM(
            //				SELECT JOB_SYS_ID,COUNT(MX_CC_RJCHK_CLEAN_BY_USR_ID) AS OPERATE,COUNT(MX_CC_RJCHK_CHECK_BY_USR_ID) AS CHECK_
            //				,COUNT(CCRR_SYS_ID) AS COUNT_
            //				FROM  BMR_RUN_JOB
            //				LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
            //				LEFT JOIN BMR_MX_RUN_JOB_CC ON CCRR_BMR_H_SYS_ID = BMR_H_SYS_ID AND JOB_SYS_ID = CCRR_JOB_SYS_ID
            //				LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK ON MX_CC_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND CCRR_RUN_NO = MX_CC_RJCHK_RUN_NO
            //				GROUP BY JOB_SYS_ID
            //				UNION
            //				SELECT JOB_SYS_ID,COUNT(MX_RJCHK_OPERATE_BY_USR_ID) AS OPERATE,COUNT(MX_RJCHK_CHECK_BY_USR_ID) AS CHECK_
            //				,COUNT(MXSR_SYS_ID) AS COUNT_
            //				FROM  BMR_RUN_JOB
            //				LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
            //				LEFT JOIN BMR_MX_RUN_JOB_MX ON MXSR_H_SYS_ID = BMR_H_SYS_ID AND JOB_SYS_ID = MXSR_JOB_SYS_ID
            //				LEFT JOIN BMR_MX_RUN_JOB_CHECK ON MX_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND MX_RJCHK_STEP = MXSR_STEP AND MXSR_RUN_NO = MX_RJCHK_RUN_NO
            //				GROUP BY JOB_SYS_ID
            //		)DATA1
            //		GROUP BY JOB_SYS_ID
            //)DATA2 ON DATA2.JOB_SYS_ID_2 = DATA1.JOB_SYS_ID";
            query = @"SELECT JOB_SYS_ID
                    ,CAST((OPERATE_PERCENT+CHECK_PERCENT) AS nvarchar)+'|'+ISNULL(CAST(JOB_APPR_PD_MX_STATUS AS nvarchar)+'|','|')+ISNULL(USER_APPR_PD_JOB_USER_NAME+'|','|')+ISNULL(JOB_APPR_PD_MX_DT,'') AS APPR_JOB_PD
                    ,CAST((OPERATE_PERCENT+CHECK_PERCENT) AS nvarchar)+'|'+ISNULL(CAST(JOB_APPR_QA_MX_STATUS AS nvarchar)+'|','|')+ISNULL(USER_APPR_QA_JOB_USER_NAME+'|','|')+ISNULL(JOB_APPR_QA_MX_DT,'') AS APPR_JOB_QA
					,SUBSTRING(CCR_GROUP_CLEAN_ID,0,LEN(CCR_GROUP_CLEAN_ID)) AS CCR_GROUP_CLEAN_ID
					,SUBSTRING(CCR_GROUP_CHECK_ID,0,LEN(CCR_GROUP_CHECK_ID)) AS CCR_GROUP_CHECK_ID
					,SUBSTRING(MXS_GROUP_OPERATE_ID,0,LEN(MXS_GROUP_OPERATE_ID)) AS MX_GROUP_OPRATE_ID
					,SUBSTRING(MXS_GROUP_CHECK_ID,0,LEN(MXS_GROUP_CHECK_ID)) AS MXS_GROUP_CHECK_ID
					,SUBSTRING(MXS_TEMP_YN,0,LEN(MXS_TEMP_YN)) as MXS_TEMP_YN
					, SUBSTRING(MXS_HUMIDITY_YN,0,LEN(MXS_HUMIDITY_YN)) as MXS_HUMIDITY_YN
					, SUBSTRING(MXS_PRESS_YN,0,LEN(MXS_PRESS_YN)) MXS_PRESS_YN
					,SUBSTRING(MXS_VACC_YN,0,LEN(MXS_VACC_YN)) MXS_VACC_YN
                    ,SUBSTRING(MXS_STARTSTOP_YN,0,LEN(MXS_STARTSTOP_YN)) as MXS_STARTSTOP_YN
					,SUBSTRING(MXS_WEIGHT_YN,0,LEN(MXS_WEIGHT_YN)) as MXS_WEIGHT_YN
                    ,SUBSTRING(MXS_WEIGHT_SAMPLE_YN,0,LEN(MXS_WEIGHT_SAMPLE_YN)) as MXS_REQ_WEIGHT_SAMPLE_YN
                    ,SUBSTRING(MXS_IMAGE_YN,0,LEN(MXS_IMAGE_YN)) as MXS_IMAGE_YN
                    ,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_ITEM_CODE+'|'+JOB_ITEM_NAME+'|'+'R'+cast(BMR_RV1 as nvarchar)+'-'+CAST(BMR_RV2 AS NVARCHAR)+'/'+CONVERT(varchar,BMR_RV_DATE,4)+
					ISNULL('|'+CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108),'|') +
					ISNULL('|'+CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108),'|')
					as JOB_ITEM_NAME2
					,JOB_LOT,BMR_VERSION
					,CONVERT(varchar,NULLIF(JOB_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_START_DT,''), 108) AS JOB_START_DT
					,CONVERT(varchar,NULLIF(JOB_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_END_DT,''), 108) AS JOB_END_DT
                    ,PARSENAME(CONVERT(varchar, CAST(JOB_BATCH_SIZE AS money), 1), 2)+' '+JOB_UOM as JOB_BATCH_SIZE
                    ,JOB_STATUS
                    ,SUBSTRING(CCR_RUN_NO,0,LEN(CCR_RUN_NO)) AS CCR_RUN_NO
                    ,SUBSTRING(CCR_EQUIPMENT_NO,0,LEN(CCR_EQUIPMENT_NO)) AS CCR_EQUIPMENT_NO
                    ,SUBSTRING(CCR_EQUIPMENT_NAME,0,LEN(CCR_EQUIPMENT_NAME)) AS CCR_EQUIPMENT_NAME
                    ,SUBSTRING(CCR_REQ_IMAGE_YN,0,LEN(CCR_REQ_IMAGE_YN)) as CCR_REQ_IMAGE_YN
                    ,SUBSTRING(MXS_STEP,0,LEN(MXS_STEP)) AS  MXS_STEP
                    ,SUBSTRING(MXS_RUN_NO,0,LEN(MXS_RUN_NO)) AS  MXS_RUN_NO
                    ,SUBSTRING(MXS_STEP_DESC,0,LEN(MXS_STEP_DESC)) AS MXS_STEP_DESC
                    ,SUBSTRING(USER_NAME_CC_CLEAN,0,LEN(USER_NAME_CC_CLEAN)) AS USER_NAME_CC_CLEAN
                    ,SUBSTRING(USER_NAME_CC_CHECK,0,LEN(USER_NAME_CC_CHECK)) AS USER_NAME_CC_CHECK
                    ,SUBSTRING(USER_NAME_MX_OPERATE,0,LEN(USER_NAME_MX_OPERATE)) AS USER_NAME_MX_OPERATE
					,SUBSTRING(USER_NAME_MX_OPERATE_DT,0,LEN(USER_NAME_MX_OPERATE_DT)) AS USER_NAME_MX_OPERATE_DT
                    ,SUBSTRING(USER_NAME_MX_CHECK,0,LEN(USER_NAME_MX_CHECK)) AS USER_NAME_MX_CHECK
                    ,SUBSTRING(USER_NAME_MX_CHECK_DT,0,LEN(USER_NAME_MX_CHECK_DT)) AS USER_NAME_MX_CHECK_DT
					,SUBSTRING(USER_NAME_CC_CLEAN_DT,0,LEN(USER_NAME_CC_CLEAN_DT)) AS USER_NAME_CC_CLEAN_DT
                    ,SUBSTRING(USER_NAME_CC_CHECK_DT,0,LEN(USER_NAME_CC_CHECK_DT)) AS USER_NAME_CC_CHECK_DT
					,OPERATE_PERCENT,CHECK_PERCENT
                    FROM(
                    SELECT distinct JOB_SYS_ID,JOB_APPR_PD_MX_STATUS,JOB_APPR_QA_MX_STATUS,JOB_CR_DT
                    ,BMR_RV1,BMR_RV2,BMR_RV_DATE
					,CONVERT(varchar,NULLIF(JOB_APPR_PD_MX_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_APPR_PD_MX_DT,''), 108)  AS  JOB_APPR_PD_MX_DT
					,USER_APPR_PD_JOB.USER_NAME AS USER_APPR_PD_JOB_USER_NAME
					,CONVERT(varchar,NULLIF(JOB_APPR_QA_MX_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(JOB_APPR_QA_MX_DT,''), 108)  AS  JOB_APPR_QA_MX_DT
					,USER_APPR_QA_JOB.USER_NAME AS USER_APPR_QA_JOB_USER_NAME
					,JOB_START_DT,BMR_VERSION,JOB_END_DT,JOB_REMARK,JOB_ITEM_CODE,JOB_ITEM_NAME,JOB_LOT,JOB_BATCH_SIZE,JOB_STATUS,JOB_UOM
					,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_TEMP_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_TEMP_YN
					,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_HUMUDITY_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_HUMIDITY_YN
					,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_PRESS_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_PRESS_YN
					,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_VACC_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_VACC_YN
					,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_STAR_STOP_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STARTSTOP_YN
					,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_WEIGHT_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_WEIGHT_YN
                    ,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_WEIGHT_SAMPLE_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_WEIGHT_SAMPLE_YN
                    ,STUFF((SELECT  ISNULL(cast(t2.MXR_REQ_IMAGE_YN as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_IMAGE_YN
					,STUFF((SELECT  ISNULL(cast(t2.MXR_CC_GROUP_CLEAN_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.MXR_CC_BMR_H_SYS_ID AND t2.MXR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.MXR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_GROUP_CLEAN_ID
					,STUFF((SELECT  ISNULL(cast(t2.MXR_CC_GROUP_CHECK_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.MXR_CC_BMR_H_SYS_ID AND t2.MXR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.MXR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_GROUP_CHECK_ID
					,STUFF((SELECT  ISNULL(cast(t2.MXR_GROUP_OPERATE_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_GROUP_OPERATE_ID
					,STUFF((SELECT  ISNULL(cast(t2.MXR_GROUP_CHECK_ID as nvarchar(max))+'|','|') from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_GROUP_CHECK_ID
                    ,STUFF((SELECT  cast(t2.MXR_CC_RUN_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.MXR_CC_BMR_H_SYS_ID AND t2.MXR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.MXR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_RUN_NO
                    ,STUFF((SELECT  cast(t2.MXR_CC_EQUIPMENT_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.MXR_CC_BMR_H_SYS_ID AND t2.MXR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.MXR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') CCR_EQUIPMENT_NO
                    ,STUFF((SELECT  cast(t2.MXR_CC_EQUIPMENT_NAME as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.MXR_CC_BMR_H_SYS_ID AND t2.MXR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.MXR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_EQUIPMENT_NAME
                    ,STUFF((SELECT  cast(t2.MXR_CC_REQ_IMAGE_YN as nvarchar(max))+'|' from BMR_MX_RUN_JOB_CC t2 where JOB_H_SYS_ID = t2.MXR_CC_BMR_H_SYS_ID AND t2.MXR_CC_JOB_SYS_ID = JOB_SYS_ID order by t2.MXR_CC_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') CCR_REQ_IMAGE_YN
                    ,STUFF((SELECT  cast(t2.MXR_STEP_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STEP
                    ,STUFF((SELECT  cast(t2.MXR_RUN_NO as nvarchar(max))+'|' from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_RUN_NO
                    ,STUFF((SELECT  cast(t2.MXR_STEP_DESC as nvarchar(max))+'|' from BMR_MX_RUN_JOB_PROCEDURE t2 where JOB_H_SYS_ID = t2.MXR_BMR_H_SYS_ID AND JOB_SYS_ID = t2.MXR_JOB_SYS_ID order by  t2.MXR_STEP_NO,MXR_RUN_NO FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') ,1,0,'') MXS_STEP_DESC
					,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_MX_RUN_JOB_CC 
							LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON MXR_CC_RUN_NO=MX_CC_RJCHK_RUN_NO and MXR_CC_JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN
					,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_CC_RJCHK_CLEAN_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_CC_RJCHK_CLEAN_BY_DT,''), 108) +'|','|')
							from BMR_MX_RUN_JOB_CC 
							LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON MXR_CC_RUN_NO=MX_CC_RJCHK_RUN_NO and MXR_CC_JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CLEAN_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CLEAN_DT
						,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_MX_RUN_JOB_CC 
							LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON MXR_CC_RUN_NO=MX_CC_RJCHK_RUN_NO and MXR_CC_JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK
						,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_CC_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_CC_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
							from BMR_MX_RUN_JOB_CC 
							LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK  ON MXR_CC_RUN_NO=MX_CC_RJCHK_RUN_NO and MXR_CC_JOB_SYS_ID = MX_CC_RJCHK_JOB_SYS_ID
							LEFT JOIN BMR_USER_CTRL ON MX_CC_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_CC_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_CC_JOB_SYS_ID
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_CC_CHECK_DT
						,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_MX_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXR_RUN_NO=MX_RJCHK_RUN_NO AND MXR_STEP_NO = MX_RJCHK_STEP and MXR_JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_JOB_SYS_ID
                            order by MXR_STEP_NO,MXR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_OPERATE
						,STUFF((SELECT  ISNULL(USER_NAME+'|','|')
							from BMR_MX_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXR_RUN_NO=MX_RJCHK_RUN_NO AND MXR_STEP_NO = MX_RJCHK_STEP and MXR_JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_JOB_SYS_ID
                            order by MXR_STEP_NO,MXR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_CHECK
						,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_RJCHK_CHECK_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJCHK_CHECK_BY_DT,''), 108) +'|','|')
							from BMR_MX_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXR_RUN_NO=MX_RJCHK_RUN_NO AND MXR_STEP_NO = MX_RJCHK_STEP and MXR_JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_CHECK_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_JOB_SYS_ID
                            order by MXR_STEP_NO,MXR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_CHECK_DT
						,STUFF((SELECT  ISNULL(CONVERT(varchar,NULLIF(MX_RJCHK_OPERATE_BY_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJCHK_OPERATE_BY_DT,''), 108) +'|','|')
							from BMR_MX_RUN_JOB_PROCEDURE  
								LEFT JOIN BMR_MX_RUN_JOB_CHECK  ON MXR_RUN_NO=MX_RJCHK_RUN_NO AND MXR_STEP_NO = MX_RJCHK_STEP and MXR_JOB_SYS_ID = MX_RJCHK_JOB_SYS_ID
								LEFT JOIN BMR_USER_CTRL ON MX_RJCHK_OPERATE_BY_USR_ID = USER_SYS_ID
							WHERE JOB_H_SYS_ID = MXR_BMR_H_SYS_ID AND JOB_SYS_ID = MXR_JOB_SYS_ID
                            order by MXR_STEP_NO,MXR_RUN_NO
							FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)'),1,0,'') AS USER_NAME_MX_OPERATE_DT
                    FROM BMR_RUN_JOB  LEFT JOIN BMR_HEAD ON JOB_H_SYS_ID = BMR_H_SYS_ID
					LEFT JOIN BMR_USER_CTRL USER_APPR_PD_JOB ON JOB_APPR_PD_MX_USR_ID=USER_APPR_PD_JOB.USER_SYS_ID
					LEFT JOIN BMR_USER_CTRL USER_APPR_QA_JOB ON JOB_APPR_QA_MX_USR_ID=USER_APPR_QA_JOB.USER_SYS_ID)DATA1
					 LEFT JOIN  (
					SELECT JOB_SYS_ID AS JOB_SYS_ID_2
							,CASE WHEN SUM(COUNT_)<=0 THEN 0 ELSE CAST((CAST(SUM(OPERATE) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) END as OPERATE_PERCENT
							,CASE WHEN SUM(COUNT_)<=0 THEN 0 ELSE CAST((CAST(SUM(CHECK_) AS float)/CAST(SUM(COUNT_) AS float))*100 AS decimal(18,2)) END as CHECK_PERCENT
							FROM(
									SELECT JOB_SYS_ID,COUNT(MX_CC_RJCHK_CLEAN_BY_USR_ID) AS OPERATE,COUNT(MX_CC_RJCHK_CHECK_BY_USR_ID) AS CHECK_
									,COUNT(MXR_CC_SYS_ID) AS COUNT_
									FROM  BMR_RUN_JOB
									LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
									LEFT JOIN BMR_MX_RUN_JOB_CC ON MXR_CC_BMR_H_SYS_ID = BMR_H_SYS_ID AND JOB_SYS_ID = MXR_CC_JOB_SYS_ID
									LEFT JOIN BMR_MX_RUN_JOB_CC_CHECK ON MX_CC_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND MXR_CC_RUN_NO = MX_CC_RJCHK_RUN_NO
                                    where MXR_CC_RUN_NO>0
									GROUP BY JOB_SYS_ID
									UNION
									SELECT JOB_SYS_ID,COUNT(MX_RJCHK_OPERATE_BY_USR_ID) AS OPERATE,COUNT(MX_RJCHK_CHECK_BY_USR_ID) AS CHECK_
									,COUNT(MXR_SYS_ID) AS COUNT_
									FROM  BMR_RUN_JOB
									LEFT JOIN BMR_HEAD ON  BMR_H_SYS_ID = JOB_H_SYS_ID
									LEFT JOIN BMR_MX_RUN_JOB_PROCEDURE ON MXR_BMR_H_SYS_ID = BMR_H_SYS_ID AND JOB_SYS_ID = MXR_JOB_SYS_ID
									LEFT JOIN BMR_MX_RUN_JOB_CHECK ON MX_RJCHK_JOB_SYS_ID = JOB_SYS_ID AND MX_RJCHK_STEP = MXR_STEP_NO AND MXR_RUN_NO = MX_RJCHK_RUN_NO
                                    where MXR_RUN_NO>0
									GROUP BY JOB_SYS_ID
							)DATA1
							GROUP BY JOB_SYS_ID
					)DATA2 ON DATA2.JOB_SYS_ID_2 = DATA1.JOB_SYS_ID
                    order by JOB_CR_DT desc";
            return query;
        }
        public String QueryGetItemNameByItemCodeFG()
        {
            //Scalar
            query = "select ITEM_NAME from OM_ITEM where ITEM_CODE = :P_ITEM_CODE and ITEM_IG_CODE='SSA FG' and ITEM_NAME NOT LIKE '%ยกเลิก%'";
            return query;
        }
        public String QueryGetItemFG()
        {
            query = "select ITEM_CODE,ITEM_NAME,'('||ITEM_CODE||') '||ITEM_NAME AS ITEM_CODE_NAME from OM_ITEM where ITEM_IG_CODE='SSA FG' and ITEM_NAME NOT LIKE '%ยกเลิก%' order by ITEM_NAME";
            return query;
        }
      //  public String QueryGetVersionByItem() {
      //      if (Convert.ToBoolean(HttpContext.Current.Session["AUTH_DISABLE_BMR"])) {
      //          query = @"select BMR_ITEM_CODE,BMR_VERSION,BMR_START_DATE,BMR_END_DATE 
      //                  from bmr_head where UPPER(BMR_ITEM_CODE) = @P_ITEM_CODE";
      //      }
      //      else {
      //          query = @"select BMR_ITEM_CODE,BMR_VERSION,BMR_START_DATE,BMR_END_DATE 
      //                  from bmr_head where UPPER(BMR_ITEM_CODE) = @P_ITEM_CODE 
						//and BMR_START_DATE <=SYSDATETIME()
						//and BMR_END_DATE >= SYSDATETIME()
      //                  and BMR_STATUS = 1";
      //      }
      //      return query;
      //  }
        public String QueryGetCleanControlByItem() {
            query = @"select MX_CC_BMR_H_SYS_ID,MX_CC_RUN_NO,MX_CC_EQUIPMENT_NO,MX_CC_EQUIPMENT_NAME,GROUP_OP.GROUP_NAME as GROUP_OP_NAME,GROUP_CHECK.GROUP_NAME as GROUP_CHECK_NAME,MX_CC_REQ_IMAGE_YN
                        from BMR_HEAD 
                        LEFT JOIN BMR_MX_CLEAN_CONTROL ON MX_CC_BMR_H_SYS_ID = BMR_H_SYS_ID
                        LEFT JOIN BMR_USER_GROUP GROUP_OP ON MX_CC_GROUP_CLEAN_ID = GROUP_OP.GROUP_ID
                        LEFT JOIN BMR_USER_GROUP GROUP_CHECK ON MX_CC_GROUP_CLEAN_ID = GROUP_CHECK.GROUP_ID
                        WHERE BMR_ITEM_CODE= @P_ITEM_CODE 
						and BMR_RV1 = @P_RV1
						and BMR_RV2 = @P_RV2
						and CONVERT(VARCHAR,BMR_RV_DATE,4) = @P_RV_DT";
            return query;
        }
        public String QueryGetMixStepByItem()
        {
            //query = @"select MX_BMR_H_SYS_ID,MX_STEP_NO,MX_RUN_NO,MX_STEP_DESC,GROUP_OP.GROUP_NAME AS GROUP_OP_NAME,GROUP_CHECK.GROUP_NAME AS GROUP_CHECK_NAME
            //            ,MX_REQ_IMAGE_YN,MX_REQ_HUMIDITY_YN,MX_REQ_PRESS_YN,MX_REQ_TEMP_YN,MX_REQ_VACC_YN,MX_REQ_START_STOP_YN,MX_REQ_WEIGHT_YN,MX_REQ_WEIGHT_SAMPLE_YN,MX_STANDARD_W
            //            from BMR_HEAD LEFT JOIN BMR_MX_PROCEDURE ON BMR_H_SYS_ID = MX_BMR_H_SYS_ID
            //            LEFT JOIN BMR_USER_GROUP GROUP_OP ON MX_GROUP_OPERATE_ID=GROUP_OP.GROUP_ID
            //            LEFT JOIN BMR_USER_GROUP GROUP_CHECK ON MX_GROUP_OPERATE_ID=GROUP_CHECK.GROUP_ID
            //            WHERE BMR_ITEM_CODE = @P_ITEM_CODE AND BMR_VERSION = @P_VERSION
            //            ORDER BY MX_STEP_NO,MX_RUN_NO";
            query = @"select MX_BMR_H_SYS_ID,MX_STEP_NO,MX_STEP_DESC,BMR_VERSION
                    ,substring(SUB_RUN_NO,0,LEN(SUB_RUN_NO)) as SUB_RUN_NO,substring(SUB_DESC,0,LEN(SUB_DESC)) as SUB_DESC
                    ,substring(SUB_GROUP_OP,0,LEN(SUB_GROUP_OP)) as SUB_GROUP_OP,substring(SUB_GROUP_CHECK,0,LEN(SUB_GROUP_CHECK)) as SUB_GROUP_CHECK
                    ,substring(SUB_REQ_IMAGE_YN,0,LEN(SUB_REQ_IMAGE_YN)) as SUB_REQ_IMAGE_YN,substring(SUB_REQ_HUMIDITY_YN,0,LEN(SUB_REQ_HUMIDITY_YN)) as SUB_REQ_HUMIDITY_YN
                    ,substring(SUB_REQ_PRESS_YN,0,LEN(SUB_REQ_PRESS_YN)) as SUB_REQ_PRESS_YN,substring(SUB_REQ_TEMP_YN,0,LEN(SUB_REQ_TEMP_YN)) as SUB_REQ_TEMP_YN
                    ,substring(SUB_REQ_VACC_YN,0,LEN(SUB_REQ_VACC_YN)) as SUB_REQ_VACC_YN,substring(SUB_REQ_START_STOP_YN,0,LEN(SUB_REQ_START_STOP_YN)) as SUB_REQ_START_STOP_YN
                    ,substring(SUB_REQ_WEIGHT_YN,0,LEN(SUB_REQ_WEIGHT_YN)) as SUB_REQ_WEIGHT_YN,substring(SUB_REQ_WEIGHT_SAMPLE_YN,0,LEN(SUB_REQ_WEIGHT_SAMPLE_YN)) as SUB_REQ_WEIGHT_SAMPLE_YN
                    from(
                    select BMR_VERSION
                        ,STUFF((select CAST(TP_DESC.MX_STEP_NO as nvarchar)+'.'+cast(TP_DESC.MX_RUN_NO as nvarchar)+'|'
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_RUN_NO
                        ,STUFF((select TP_DESC.MX_STEP_DESC+'|'
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_DESC
                        ,STUFF((select ISNULL(TP_GROUP_OP.GROUP_NAME+'|','|')
							from  BMR_MX_PROCEDURE TP_DESC  
							LEFT JOIN  BMR_USER_GROUP TP_GROUP_OP  ON TP_DESC.MX_GROUP_OPERATE_ID=TP_GROUP_OP.GROUP_ID
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_GROUP_OP
                        ,STUFF((select ISNULL(TP_GROUP_OP.GROUP_NAME+'|','|')
							from  BMR_MX_PROCEDURE TP_DESC  
							LEFT JOIN  BMR_USER_GROUP TP_GROUP_OP  ON TP_DESC.MX_GROUP_CHECK_ID=TP_GROUP_OP.GROUP_ID
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE ).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_GROUP_CHECK
                        ,STUFF((select ISNULL(TP_DESC.MX_REQ_IMAGE_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_IMAGE_YN
                        ,STUFF((select ISNULL(TP_DESC.MX_REQ_HUMIDITY_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE ).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_HUMIDITY_YN
                        ,STUFF((select ISNULL(TP_DESC.MX_REQ_PRESS_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_PRESS_YN
						,STUFF((select ISNULL(TP_DESC.MX_REQ_TEMP_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_TEMP_YN
						,STUFF((select ISNULL(TP_DESC.MX_REQ_VACC_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_VACC_YN
						,STUFF((select ISNULL(TP_DESC.MX_REQ_START_STOP_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_START_STOP_YN
						,STUFF((select ISNULL(TP_DESC.MX_REQ_WEIGHT_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_WEIGHT_YN
						,STUFF((select ISNULL(TP_DESC.MX_REQ_WEIGHT_SAMPLE_YN+'|','N|')
							from  BMR_MX_PROCEDURE TP_DESC 
							where TP_DESC.MX_BMR_H_SYS_ID=BMR_H_SYS_ID
							and TP_DESC.MX_STEP_NO=TP_MAIN.MX_STEP_NO
							and TP_DESC.MX_RUN_NO>0
                            FOR XML PATH(''), TYPE).value('.', 'NVARCHAR(MAX)') 
                        ,1,0,'') SUB_REQ_WEIGHT_SAMPLE_YN
                        ,MX_BMR_H_SYS_ID,MX_STEP_NO,MX_RUN_NO,MX_STEP_DESC,GROUP_OP.GROUP_NAME AS GROUP_OP_NAME
                        ,GROUP_CHECK.GROUP_NAME AS GROUP_CHECK_NAME
                        ,MX_REQ_IMAGE_YN,MX_REQ_HUMIDITY_YN,MX_REQ_PRESS_YN,MX_REQ_TEMP_YN,MX_REQ_VACC_YN
                        ,MX_REQ_START_STOP_YN,MX_REQ_WEIGHT_YN,MX_REQ_WEIGHT_SAMPLE_YN,MX_STANDARD_W
                        from BMR_HEAD LEFT JOIN BMR_MX_PROCEDURE TP_MAIN ON BMR_H_SYS_ID = MX_BMR_H_SYS_ID
                        LEFT JOIN BMR_USER_GROUP GROUP_OP ON MX_GROUP_OPERATE_ID=GROUP_OP.GROUP_ID
                        LEFT JOIN BMR_USER_GROUP GROUP_CHECK ON MX_GROUP_OPERATE_ID=GROUP_CHECK.GROUP_ID
                        WHERE BMR_ITEM_CODE = @P_ITEM_CODE 
                        and BMR_RV1 = @P_RV1
						and BMR_RV2 = @P_RV2
						and CONVERT(VARCHAR,BMR_RV_DATE,4) = @P_RV_DT
                        and MX_RUN_NO=0)data1
                        ORDER BY MX_STEP_NO,MX_RUN_NO";
            return query;
        }
        public String InsertRunJob() {
            query = @"EXEC INSERT_BMR_RUN_JOB @ITEM_CODE = @P_ITEM_CODE,@ITEM_NAME = @P_ITEM_NAME,@UOM = @P_UOM,@RV1 = @P_RV1,@RV2 = @P_RV2,@RV_DATE = @P_RV_DATE,@LOT = @P_LOT,@BATCH_SIZE = @P_BATCH_SIZE,@REMARK = @P_REMARK , @USER_ID = @P_USER_ID,@START_DT =  @P_START_DT,@END_DT = @P_END_DT";
            return query;
        }
        public String InsertTemp() {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_TEMP @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@TEMP = @P_TEMP,@USER_ID = @P_USER_ID";
            return query;
        }
        public String InsertPressure()
        {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_PRESSURE @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@PRESSURE = @P_PRESSURE,@USER_ID = @P_USER_ID";
            return query;
        }
        public String InsertRunJobTime() {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_TIME @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@START_DT = @P_START_DT,@END_DT = @P_END_DT,@RPM = @P_RPM,@USER_ID = @P_USER_ID,@LENGTH = @P_LENGTH,@STATUS_OPERATE = @P_STATUS_OPERATE";
            return query;
        }
        public String InsertRunJobVacuum()
        {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_VACUUM @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@VACUUM = @P_VACUUM,@USER_ID = @P_USER_ID";
            return query;
        }
            public String InsertHumidity()
        {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_HUMIDITY @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@HUMIDITY = @P_HUMIDITY,@USER_ID = @P_USER_ID";
            return query;
        }
        public String InsertRunJobWeight() {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_WEIGHT @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@CONTAINER_NO = @P_CONTAINER_NO,@TOTAL_WEIGHT = @P_TOTAL_WEIGHT,@TARE_WEIGHT = @P_TARE_WEIGHT,@NET_WEIGHT = @P_NET_WEIGHT,@S_TOTAL_WEIGHT = @P_S_TOTAL_WEIGHT,@S_THEORETICAL = @P_S_THEORETICAL,@S_YIELD = @P_S_YIELD,@USER_ID = @P_USER_ID,@LENGTH = @P_LENGTH,@STATUS_OPERATE = @P_STATUS_OPERATE";
            return query;
        }
        public String InsertRunJobWeightOfSample()
        {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_WEIGHT_SAMPLE @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@WEIGHT = @P_WEIGHT,@USER_ID = @P_USER_ID";
            return query;
        }
        public String QueryRunJobTemp() {
            //Scalar
            query = "SELECT MX_RJT_TEMP FROM BMR_MX_RUN_JOB_TEMP WHERE MX_RJT_JOB_SYS_ID  = @P_JOB_SYS_ID AND MX_RJT_STEP_NO = @P_STEP AND MX_RJT_RUN_NO= @P_RUN_NO";
            return query;
        }
        public String QueryRunJobPressure()
        {
            //Scalar
            query = "SELECT MX_RJP_PRESSURE FROM BMR_MX_RUN_JOB_PRESSURE WHERE MX_RJP_JOB_SYS_ID = @P_JOB_SYS_ID AND MX_RJP_STEP_NO = @P_STEP AND MX_RJP_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String QueryRunJobHumidity() {
            //Scalar
            query = "SELECT MX_RJH_HUMIDITY FROM BMR_MX_RUN_JOB_HUMIDITY WHERE MX_RJH_JOB_SYS_ID = @P_JOB_SYS_ID AND MX_RJH_STEP_NO = @P_STEP AND MX_RJH_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String QueryRunJobVacuum()
        {
            //Scalar
            query = "SELECT MX_RJV_VACUUM_RATE FROM BMR_MX_RUN_JOB_VACUUM WHERE MX_RJV_JOB_SYS_ID = @P_JOB_SYS_ID AND MX_RJV_STEP_NO = @P_STEP AND MX_RJV_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String QueryRunJobWeightOfSample() {
            //Scalar
            query = "SELECT MX_RJWS_WEIGHT FROM BMR_MX_RUN_JOB_WEIGHT_SAMPLE WHERE MX_RJWS_JOB_SYS_ID = @P_JOB_SYS_ID AND MX_RJWS_STEP_NO = @P_STEP AND MX_RJWS_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String QueryRunJobTime()
        {
            //query = @"SELECT RJDT_JOB_SYS_ID,RJDT_STEP,RJDT_RUN_NO,RJDT_LIST_NO,RJDT_RPM
            //          ,CONVERT(varchar,NULLIF(RJDT_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(RJDT_START_DT,''), 108) as RJDT_START_DT
            //          ,CONVERT(varchar,NULLIF(RJDT_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(RJDT_END_DT,''), 108) as RJDT_END_DT 
            //          FROM BMR_RUN_JOB_TIME 
            //          WHERE RJDT_JOB_SYS_ID = @P_JOB_SYS_ID AND RJDT_STEP = @P_STEP AND RJDT_RUN_NO = @P_RUN_NO";

            query = @"SELECT MX_RJDT_JOB_SYS_ID,MX_RJDT_STEP_NO,MX_RJDT_RUN_NO,MX_RJDT_LIST_NO,MX_RJDT_RPM
                    ,CONVERT(varchar,NULLIF(MX_RJDT_START_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJDT_START_DT,''), 108) as MX_RJDT_START_DT
                    ,CONVERT(varchar,NULLIF(MX_RJDT_END_DT,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJDT_END_DT,''), 108) as MX_RJDT_END_DT 
                    ,USER_NAME_OPERATE,USER_NAME_CHECK,CONVERT(varchar,NULLIF(MX_RJDT_CHECK_BY_DT_CHECK,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJDT_CHECK_BY_DT_CHECK,''), 108)  AS MX_RJDT_CHECK_BY_DT_CHECK
                    FROM BMR_MX_RUN_JOB_TIME
                    LEFT JOIN (
			                    SELECT MX_RJDT_JOB_SYS_ID AS MX_RJDT_JOB_SYS_ID_OPRATE,MX_RJDT_STEP_NO AS MX_RJDT_STEP_NO_OPERATE
			                    ,MX_RJDT_RUN_NO AS MX_RJDT_RUN_NO_OPERATE,MX_RJDT_LIST_NO AS MX_RJDT_LIST_NO_OPERATE,USER_NAME AS USER_NAME_OPERATE
			                    FROM BMR_MX_RUN_JOB_TIME LEFT JOIN BMR_USER_CTRL ON MX_RJDT_OPERATE_BY_USR_ID = USER_SYS_ID
		                      )DATAOPERATE ON MX_RJDT_JOB_SYS_ID_OPRATE = MX_RJDT_JOB_SYS_ID 
			                      and MX_RJDT_STEP_NO_OPERATE = MX_RJDT_STEP_NO
			                      and MX_RJDT_RUN_NO_OPERATE = MX_RJDT_RUN_NO 
			                      and MX_RJDT_LIST_NO_OPERATE = MX_RJDT_LIST_NO
                    LEFT JOIN (
	  		                    SELECT MX_RJDT_JOB_SYS_ID AS MX_RJDT_JOB_SYS_ID_CHECK,MX_RJDT_STEP_NO AS MX_RJDT_STEP_NO_CHECK,MX_RJDT_RUN_NO AS MX_RJDT_RUN_NO_CHECK
			                    ,MX_RJDT_LIST_NO AS MX_RJDT_LIST_NO_CHECK,USER_NAME AS USER_NAME_CHECK,MX_RJDT_CHECK_BY_DT as MX_RJDT_CHECK_BY_DT_CHECK
			                    FROM BMR_MX_RUN_JOB_TIME LEFT JOIN BMR_USER_CTRL ON MX_RJDT_CHECK_BY_USR_ID = USER_SYS_ID
		                      )DATACHECK ON MX_RJDT_JOB_SYS_ID_CHECK = MX_RJDT_JOB_SYS_ID 
			                      and MX_RJDT_STEP_NO_CHECK = MX_RJDT_STEP_NO
			                      and MX_RJDT_RUN_NO_CHECK = MX_RJDT_RUN_NO 
			  and MX_RJDT_LIST_NO_CHECK = MX_RJDT_LIST_NO
                WHERE MX_RJDT_JOB_SYS_ID = @P_JOB_SYS_ID AND MX_RJDT_STEP_NO = @P_STEP AND MX_RJDT_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String QueryRunJobWeight()
        {
            //query = @"SELECT RJW_JOB_SYS_ID,RJW_STEP,RJW_RUN_NO,RJW_LIST_NO,RJW_CONTAINER_NO,RJW_TOTAL_WEIGHT
            //          ,RJW_TARE_WEIGHT,RJW_NET_WEIGHT,RJW_S_TOTAL_WEIGHT,RJW_S_THEORETICAL_WEIGHT,RJW_S_YIELD
            //          FROM BMR_RUN_JOB_WEIGHT
            //          WHERE RJW_JOB_SYS_ID = @P_JOB_SYS_ID AND RJW_STEP = @P_STEP AND RJW_RUN_NO = @P_RUN_NO";
            query = @"SELECT MX_RJW_JOB_SYS_ID,MX_RJW_STEP_NO,MX_RJW_RUN_NO,MX_RJW_LIST_NO,MX_RJW_CONTAINER_NO,MX_RJW_TOTAL_WEIGHT
                    ,MX_RJW_TARE_WEIGHT,MX_RJW_NET_WEIGHT,MX_RJW_S_TOTAL_WEIGHT,MX_RJW_S_THEORETICAL_WEIGHT,MX_RJW_S_YIELD
                    ,USER_NAME_OPERATE,USER_NAME_CHECK,CONVERT(varchar,NULLIF(MX_RJW_CHECK_BY_DT_CHECK,''),103)+' '+CONVERT(VARCHAR(5), NULLIF(MX_RJW_CHECK_BY_DT_CHECK,''), 108)  AS MX_RJW_CHECK_BY_DT_CHECK
                    FROM BMR_MX_RUN_JOB_WEIGHT
                    LEFT JOIN (
			                    SELECT MX_RJW_JOB_SYS_ID AS MX_RJW_JOB_SYS_ID_OPRATE,MX_RJW_STEP_NO AS MX_RJW_STEP_NO_OPERATE
			                    ,MX_RJW_RUN_NO AS MX_RJW_RUN_NO_OPERATE,MX_RJW_LIST_NO AS MX_RJW_LIST_NO_OPERATE,USER_NAME AS USER_NAME_OPERATE
			                    FROM BMR_MX_RUN_JOB_WEIGHT LEFT JOIN BMR_USER_CTRL ON MX_RJW_OPERATE_BY_USR_ID = USER_SYS_ID
		                      )DATAOPERATE ON MX_RJW_JOB_SYS_ID_OPRATE = MX_RJW_JOB_SYS_ID 
			                      and MX_RJW_STEP_NO_OPERATE = MX_RJW_STEP_NO
			                      and MX_RJW_RUN_NO_OPERATE = MX_RJW_RUN_NO 
			                      and MX_RJW_LIST_NO_OPERATE = MX_RJW_LIST_NO
                    LEFT JOIN (
	  		                    SELECT MX_RJW_JOB_SYS_ID AS MX_RJW_JOB_SYS_ID_CHECK,MX_RJW_STEP_NO AS MX_RJW_STEP_NO_CHECK,MX_RJW_RUN_NO AS MX_RJW_RUN_NO_CHECK
			                    ,MX_RJW_LIST_NO AS MX_RJW_LIST_NO_CHECK,USER_NAME AS USER_NAME_CHECK,MX_RJW_CHECK_BY_DT as MX_RJW_CHECK_BY_DT_CHECK
			                    FROM BMR_MX_RUN_JOB_WEIGHT LEFT JOIN BMR_USER_CTRL ON MX_RJW_CHECK_BY_USR_ID = USER_SYS_ID
		                      )DATACHECK ON MX_RJW_JOB_SYS_ID_CHECK = MX_RJW_JOB_SYS_ID 
			                      and MX_RJW_STEP_NO_CHECK = MX_RJW_STEP_NO
			                      and MX_RJW_RUN_NO_CHECK = MX_RJW_RUN_NO 
			  and MX_RJW_LIST_NO_CHECK = MX_RJW_LIST_NO
                WHERE MX_RJW_JOB_SYS_ID = @P_JOB_SYS_ID AND MX_RJW_STEP_NO = @P_STEP AND MX_RJW_RUN_NO = @P_RUN_NO";
            return query;
        }
            public String QueryGetUomBomSF()
        {
            //query = @"SELECT ITEM_CODE3 AS item_,DECODE(BI_ITEM_TYPE,'PM','01','SM','02','SF','02','RM','03',BI_ITEM_TYPE) AS NO_,BI_ITEM_TYPE AS GROUP_ 
            //                ,ITEM_CODE,ITEM_NAME,BOM_CODE,BOM_NAME,BI_ITEM_CODE,ITEM_NAME2,BI_QTY,BI_QTY_LS,BI_QTY_BU,BI_UOM_CODE,LOOSE,IU_CONV_FACTOR 
            //                ,BOM_QTY,BOM_UOM_CODE 
            //        FROM OM_ITEM,OM_BOM,OM_BOM_ITEM_DETAIL, 
            //            (SELECT ITEM_CODE ITEM_CODE2,ITEM_NAME ITEM_NAME2,NVL(IU_MAX_LOOSE_1,1) LOOSE,IU_CONV_FACTOR,IU_UOM_CODE 
            //             FROM OM_ITEM,OM_ITEM_UOM 
            //             WHERE IU_ITEM_CODE = ITEM_CODE),
            //            (SELECT DISTINCT BI_ITEM_CODE AS BI_ITEM_CODE3,ITEM_CODE AS ITEM_CODE3
            //             FROM OM_ITEM,OM_BOM,OM_BOM_ITEM_DETAIL
            //             WHERE BOM_ITEM_CODE = ITEM_CODE
            //             AND BI_BOM_CODE = BOM_CODE 
            //             AND BI_ITEM_TYPE IN('SM','SF')) 
            //        WHERE ITEM_CODE = BI_ITEM_CODE3 
            //        AND BOM_ITEM_CODE = ITEM_CODE
            //        AND BI_BOM_CODE = BOM_CODE 
            //        AND ITEM_CODE2 = BI_ITEM_CODE 
            //        AND BI_UOM_CODE = IU_UOM_CODE 
            //        AND ITEM_CODE3 = :P_ITEM_CODE";
            query = @"SELECT DISTINCT BOM_UOM_CODE
                    FROM OM_ITEM,OM_BOM,OM_BOM_ITEM_DETAIL, 
                        (SELECT ITEM_CODE ITEM_CODE2,ITEM_NAME ITEM_NAME2,NVL(IU_MAX_LOOSE_1,1) LOOSE,IU_CONV_FACTOR,IU_UOM_CODE 
                         FROM OM_ITEM,OM_ITEM_UOM 
                         WHERE IU_ITEM_CODE = ITEM_CODE),
                        (SELECT DISTINCT BI_ITEM_CODE AS BI_ITEM_CODE3,ITEM_CODE AS ITEM_CODE3
                         FROM OM_ITEM,OM_BOM,OM_BOM_ITEM_DETAIL
                         WHERE BOM_ITEM_CODE = ITEM_CODE
                         AND BI_BOM_CODE = BOM_CODE 
                         AND BI_ITEM_TYPE IN('SM','SF')) 
                    WHERE ITEM_CODE = BI_ITEM_CODE3 
                    AND BOM_ITEM_CODE = ITEM_CODE
                    AND BI_BOM_CODE = BOM_CODE 
                    AND ITEM_CODE2 = BI_ITEM_CODE 
                    AND BI_UOM_CODE = IU_UOM_CODE 
                    AND ITEM_CODE3 = :P_ITEM_CODE";
            return query;
        }

        public String QueryInsertHeadBMR() {

            query = "EXEC INSERT_BMR_HEAD @ITEM_CODE = @P_ITEM_CODE,@ITEM_NAME = @P_ITEM_NAME,@START_DT = @P_START_DT,@END_DT = @P_END_DT,@BMR_RV1 = @P_BMR_RV1,@BMR_RV2 = @P_BMR_RV2,@BMR_RV_DATE = @P_BMR_RV_DATE,@USR_ID = @P_USR_ID";
            return query;
        }

        public String QuerySaveExcelCleanControlRecord()
        {
            //query = "EXEC INSERT_CLEAN_CONTROL @ITEM_CODE = @P_ITEM_CODE,@RUN_NO = @P_RUN_NO,@EQUIPMENT_NO  = @P_EQUIPMENT_NO,@EQUIPMENT_NAME = @P_EQUIPMENT_NAME,@USER_BY  = @P_USER_BY,@USER_DT = @P_USER_DT,@CHECK_BY = @P_CHECK_BY,@CHECK_DT  = @P_CHECK_DT,@REQUIRE_YN = @P_REQUIRE_YN,@LOT_NO = @P_LOT_NO,@GROUP_OPERATE_ID = @P_GROUP_OPERATE_ID,@GROUP_CHECK_ID = @P_GROUP_CHECK_ID";
            query = "EXEC INSERT_BMR_MX_CLEAN_CONTROL @ITEM_CODE = @P_ITEM_CODE,@RUN_NO = @P_RUN_NO,@EQUIPMENT_NO = @P_EQUIPMENT_NO,@EQUIPMENT_NAME = @P_EQUIPMENT_NAME,@REQ_IMAGE_YN = @P_REQ_IMAGE_YN,@GROUP_OPERATE_ID = @P_GROUP_OPERATE_ID,@GROUP_CHECK_ID = @P_GROUP_CHECK_ID,@USER_ID = @P_USER_ID";

            return query;
        }
        public String QuerySaveExcelMixStep()
        {
            //query = "EXEC INSERT_MIX_STEP @ITEM_CODE = @P_ITEM_CODE,@RUN_NO = @P_RUN_NO,@STEP  = @P_STEP,@STEP_DESC =  @P_STEP_DESC,@USER_BY = @P_USER_BY,@USER_DT = @P_USER_DT,@CHECK_BY = @P_CHECK_BY,@CHECK_DT = @P_CHECK_DT,@REQUIRED_YN = @P_REQUIRED_YN,@TEMP_ENV = @P_TEMP_ENV,@HUMUDITY_ENV = @P_HUMUDITY_ENV,@PRESSURE_ENV = @P_PRESSURE_ENV,@REQ_TEMP_ENV_YN = @P_REQ_TEMP_ENV_YN,@REQ_HUMUDITY_YN = @P_REQ_HUMUDITY_YN,@REQ_PRESS_YN = @P_REQ_PRESS_YN,@TEMP = @P_TEMP,@REQ_TEMP_YN = @P_REQ_TEMP_YN,@VACC_RATE = @P_VACC_RATE,@REQ_VACC_YN = @P_REQ_VACC_YN,@REQ_STAR_STOP_YN = @P_REQ_STAR_STOP_YN,@RESULT = @P_RESULT,@REQ_RESULT_YN = @P_REQ_RESULT_YN,@REQ_WEIGHT = @P_REQ_WEIGHT,@STANDARD_W = @P_STANDARD_W,@REQ_WEIGHT_SAMPLE_YN = @P_REQ_WEIGHT_SAMPLE_YN,@GROUP_OPERATE_ID = @P_GROUP_OPERATE_ID,@GROUP_CHECK_ID = @P_GROUP_CHECK_ID";
            query = "EXEC INSERT_BMR_MX @ITEM_CODE = @P_ITEM_CODE,@RUN_NO = @P_RUN_NO,@STEP_NO = @P_STEP_NO,@STEP_DESC = @P_STEP_DESC,@STEP_DESC_ENG = @P_STEP_DESC_ENG,@REQ_IMAGE_YN = @P_REQ_IMAGE_YN,@REQ_HUMUDITY_YN = @P_REQ_HUMUDITY_YN,@REQ_PRESS_YN = @P_REQ_PRESS_YN,@REQ_TEMP_YN = @P_REQ_TEMP_YN,@REQ_VACC_YN = @P_REQ_VACC_YN,@REQ_STAR_STOP_YN = @P_REQ_STAR_STOP_YN,@REQ_WEIGHT_YN = @P_REQ_WEIGHT_YN,@STANDARD_W = @P_STANDARD_W,@REQ_WEIGHT_SAMPLE_YN = @P_REQ_WEIGHT_SAMPLE_YN,@GROUP_OPERATE_ID = @P_GROUP_OPERATE_ID,@GROUP_CHECK_ID = @P_GROUP_CHECK_ID,@USER_ID = @P_USER_ID";
            return query;
        }
        //public String QueryGetMixStep()
        //{
        //    query = @"SELECT MXS_SYS_ID,FG_CODE,RUN_NO,STEP,STEP_DESC,USER_BY,USER_DT,CHECK_BY
        //            ,CHECK_DT,REQUIRED_YN,TEMP_ENV,HUMUDITY_ENV,PRESSURE_ENV,REQ_TEMP_ENV_YN
        //            ,REQ_HUMUDITY_YN,REQ_PRESS_YN,TEMP,REQ_TEMP_YN,VACC_RATE,REQ_VACC_YN,START_DT
        //            ,END_DT,REQ_STAR_STOP_YN,RESULT,REQ_RESULT_YN,REQ_WEIGHT,STANDARD_W
        //            FROM MIX_STEP where fg_code = :P_MIX_FG_CODE and REQUIRED_YN = :P_MIX_REQ_YN";
        //    return query;
        //}
        //public String QueryGetControl()
        //{
        //    query = @"SELECT CCR_SYS_ID,FG_CODE,RUN_NO,EQUIPMENT_NO,EQUIPMENT_NAME
        //            ,USER_BY,USER_DT,CHECK_BY,CHECK_DT,REQUIRE_YN,LOT_NO
        //            FROM CLEAN_CONTROL_RECORD where FG_CODE = :P_CT_FG_CODE and REQUIRE_YN = :P_CT_REQUIRE_YN";
        //    return query;
        //}
        //public String QuerySaveVersion()
        //{
        //    query = @"SELECT ITEM_CODE,ITME_NAME FROM OM_ITEM where item_code = :P_ITEM_CODE or item_name = :P_ITEM_NAME";
        //    return query;
        //}

        //public String QueryGetVersion() {
        //    query = @"select distinct FG_CODE,VERSION_ from MIX_STEP where FG_CODE = @P_FG_CODE";
        //    return query;
        //}
        public String QueryRunJobImage()
        {
            query = @"SELECT MX_RJPT_SYS_ID,MX_RJPT_IMAGE_NAME,MX_RJPT_LIST_NO,MX_RJPT_IMAGE_PATH,MX_RJPT_REMARK 
                      FROM BMR_MX_RUN_JOB_PICTURE 
                      WHERE MX_RJPT_JOB_SYS_ID =@P_SYS_ID AND MX_RJPT_STEP_NO = @P_STEP AND MX_RJPT_RUN_NO =@P_RUNNO";
            return query;
        }
        public String QueryCCRunJobImage() {
            query = @"SELECT MX_CC_RJPT_SYS_ID,MX_CC_RJPT_IMAGE_NAME,MX_CC_RJPT_LIST_NO,MX_CC_RJPT_IMAGE_PATH,MX_CC_RJPT_REMARK
                      FROM BMR_MX_RUN_JOB_CC_PICTURE
                      WHERE MX_CC_RJPT_JOB_SYS_ID =@P_SYS_ID  AND MX_CC_RJPT_RUN_NO =@P_RUNNO";
            return query;
        }
        public String InsertRunJobImage()
        {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_IMAGE @JOB_SYS_ID = @P_JOB_SYS_ID,@STEP = @P_STEP,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@LENGTH = @P_LENGTH,@IMAGE_NAME = @P_IMAGE_NAME,@IMAGE_PATH = @P_IMAGE_PATH,@IMAGE_REMARK = @P_REMARK,@USER_ID = @P_USERID";
            return query;
        }
        public String CCInsertRunJobImage()
        {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_CC_IMAGE @JOB_SYS_ID = @P_JOB_SYS_ID,@RUN_NO = @P_RUN_NO,@LIST_NO = @P_LIST_NO,@LENGTH = @P_LENGTH,@IMAGE_NAME = @P_IMAGE_NAME,@IMAGE_PATH = @P_IMAGE_PATH,@IMAGE_REMARK = @P_REMARK,@USER_ID = @P_USERID";
            return query;
        }
        public String CCUpdateRunJobImage() {
            //Remark
            query = "UPDATE BMR_MX_RUN_JOB_CC_PICTURE SET MX_CC_RJPT_REMARK = @P_REMARK,MX_CC_RJPT_UPD_USR_ID = @P_USER_ID,MX_CC_RJPT_UPD_DT = SYSDATETIME() WHERE MX_CC_RJPT_JOB_SYS_ID = @P_JOB_SYS_ID AND  MX_CC_RJPT_RUN_NO = @P_RUN_NO";
            return query;
        }
        public String ApprPdJob() {
            query = "EXEC APPR_PD_MX_RUN_JOB @JOB_SYS_ID = @P_JOB_SYS_ID,@USER_ID = @P_USER_ID ,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String ApprQaJob()
        {
            query = "EXEC APPR_QA_MX_RUN_JOB @JOB_SYS_ID = @P_JOB_SYS_ID,@USER_ID = @P_USER_ID ,@USER_LOGIN = @P_USER_LOGIN,@USER_PASS = @P_USER_PASS";
            return query;
        }
        public String InsertRunJobCC() {
            query = "EXEC INSERT_BMR_MX_RUN_JOB_CC @JOB_SYS_ID = @P_JOB_SYS_ID,@RUN_NO = @P_RUN_NO,@EQUIPMENT_NO = @P_EQUIPMENT_NO,@EQUIPMENT_NAME = @P_EQUIPMENT_NAME,@GROUP_CLEAN = @P_GROUP_CLEAN,@GROUP_CHECK = @P_GROUP_CHECK,@REQ_IMAGE_YN = @P_REQ_IMAGE_YN,@USER_ID = @P_USER_ID";
            return query;
        }
        //public String InsertBmrMxHead() {
        //    query = "EXEC INSERT_BMR_MX_HEAD @ITEM_CODE = @P_ITEM_CODE,@ITEM_NAME = @P_ITEM_NAME,@LOT = @P_LOT,@START_DT = @P_START_DT,@END_DT = @P_END_DT,@RV1 = @P_RV1,@RV2 = @P_RV2,@EFF_DT = @P_EFF_DT,@USER_ID = @P_USER_ID";
        //    return query;
        //}
    }
}